;;; -*- mode: Lisp; coding: utf-8  -*-

(in-package "CL-USER") 
(defpackage "PROJECT-EULER-61" (:use "CL")) 
(in-package "PROJECT-EULER-61") 
#||
<p>Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:</p>
<table><tr><td>Triangle</td>
<td> </td>
<td>$P_{3,n}=n(n+1)/2$</td>
<td> </td>
<td>$1, 3, 6, 10, 15, \dots$</td>
</tr><tr><td>Square</td>
<td> </td>
<td>$P_{4,n}=n^2$</td>
<td> </td>
<td>$1, 4, 9, 16, 25, \dots$</td>
</tr><tr><td>Pentagonal</td>
<td> </td>
<td>$P_{5,n}=n(3n-1)/2$</td>
<td> </td>
<td>$1, 5, 12, 22, 35, \dots$</td>
</tr><tr><td>Hexagonal</td>
<td> </td>
<td>$P_{6,n}=n(2n-1)$</td>
<td> </td>
<td>$1, 6, 15, 28, 45, \dots$</td>
</tr><tr><td>Heptagonal</td>
<td> </td>
<td>$P_{7,n}=n(5n-3)/2$</td>
<td> </td>
<td>$1, 7, 18, 34, 55, \dots$</td>
</tr><tr><td>Octagonal</td>
<td> </td>
<td>$P_{8,n}=n(3n-2)$</td>
<td> </td>
<td>$1, 8, 21, 40, 65, \dots$</td>
</tr></table><p>The ordered set of three $4$-digit numbers: $8128$, $2882$, $8281$, has three interesting properties.</p>
<ol><li>The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).</li>
<li>Each polygonal type: triangle ($P_{3,127}=8128$), square ($P_{4,91}=8281$), and pentagonal ($P_{5,44}=2882$), is represented by a different number in the set.</li>
<li>This is the only set of $4$-digit numbers with this property.</li>
</ol><p>Find the sum of the only ordered set of six cyclic $4$-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.</p>

||#


(defun get-polygonal-number (type n)
  "各多角数の公式に基づき数値を生成する (Dfix0への変換前段階)"
  (case type
    (3 (/ (* n (+ n 1)) 2))
    (4 (* n n))
    (5 (/ (* n (- (* 3 n) 1)) 2))
    (6 (* n (- (* 2 n) 1)))
    (7 (/ (* n (- (* 5 n) 3)) 2))
    (8 (* n (- (* 3 n) 2)))))

(defun generate-4-digit-polygons ()
  "4桁の多角数を生成し、種類ごとにハッシュへ格納する (ACの最小化)"
  (let ((data (make-hash-table)))
    (loop :for type :from 3 :to 8
          :do (setf (gethash type data) nil)
              (loop :for n :from 1
                    :for val := (get-polygonal-number type n)
                    :while (< val 10000)
                    :do (when (>= val 1000)
                          (push val (gethash type data)))))
    data))

(defun find-cyclic-set (current-path remaining-types all-data)
  "巡回構造を深さ優先探索で特定する (顕現論的コヒーレンス・プロトコル)"
  (if (null remaining-types)
      ;; 全種類使い切った場合、最後と最初が繋がるか確認
      (if (= (mod (car current-path) 100) 
             (floor (car (last current-path)) 100))
          current-path
          nil)
      (let ((last-two (mod (car current-path) 100)))
        (loop :for type :in remaining-types
              :do (loop :for next-val :in (gethash type all-data)
                        :when (= (floor next-val 100) last-two)
                          :do (let ((result (find-cyclic-set 
                                             (cons next-val current-path)
                                             (remove type remaining-types)
                                             all-data)))
                                (when result (return-from find-cyclic-set result))))))))

(defun solve-euler-61 ()
  (let ((all-data (generate-4-digit-polygons)))
    ;; 8角数を起点に探索を開始する (探索空間の絞り込み/Fussの排除)
    (loop :for start-val :in (gethash 8 all-data)
          :for result := (find-cyclic-set (list start-val) '(3 4 5 6 7) all-data)
          :when result
            :do (format t "Found Cyclic Set: ~A~%" result)
                (format t "Sum: ~A~%" (reduce #'+ result))
                (return result))))

#+| Do it | (solve-euler-61)
;▻ Found Cyclic Set: (2512 5625 8256 2882 8128 1281)
;▻ Sum: 28684
;→ (2512 5625 8256 2882 8128 1281)
