;;; -*- mode: Lisp; coding: utf-8 -*-
;;; llm-model: gemini-3.1-pro
(cl:in-package cl-user)
(defpackage #:project-euler-0696 (:use cl series alexandria) (:export #:solve))
(in-package #:project-euler-0696)
(eval-when (:compile-toplevel :load-toplevel :execute) (series::install))

(declaim (optimize (speed 3) (safety 0) (debug 0) (hcl:fixnum-safety 0)))

(defconstant $const-modulo 1000000007)
(defconstant $max-tiles-per-suit 93)   ;; t=30のとき1スートの最大牌数は 3*30+2 = 92。配列サイズは93
(defconstant $max-dfa-states 500)      ;; 最小化前DFA状態数の安全なバッファ上限
(defconstant $num-tile-transitions 5)  ;; 1つの数位に対する牌の枚数は0枚〜4枚 (計5パターン)
(defconstant $nfa-num-states 18)       ;; NFAの状態数 (c1=0..2) * (c2=0..2) * (p=0..1) = 18

(defun make-fixnum-array (size-n)
  "指定されたサイズの fixnum 型 1次元配列を生成する"
  (make-array size-n :element-type 'fixnum :initial-element 0))

(defun get-nfa-transitions ()
  "NFAの遷移表を構築する"
  (let ((trans-table (make-array (list $nfa-num-states $num-tile-transitions) :initial-element nil)))
    (iterate ((count1 (scan-range :from 0 :below 3)))
      (iterate ((count2 (scan-range :from 0 :below 3)))
        (iterate ((pair-flag (scan-range :from 0 :below 2)))
          (let ((state-id (+ (* count1 6) (* count2 2) pair-flag)))
            (iterate ((tiles (scan-range :from 0 :below $num-tile-transitions)))
              (let ((next-states nil))
                (iterate ((count3 (scan-range :from 0 :below 3)))
                  (iterate ((pung-flag (scan-range :from 0 :below 2)))
                    (iterate ((new-pair (scan-range :from 0 :below 2)))
                      (when (and (<= (+ pair-flag new-pair) 1)
                                 (= (+ count1 count2 count3 (* 3 pung-flag) (* 2 new-pair)) tiles))
                        (push (+ (* count2 6) (* count3 2) (+ pair-flag new-pair)) next-states)))))
                (setf (aref trans-table state-id tiles) (remove-duplicates next-states))))))))
    trans-table))

(defun build-dfa ()
  "NFAからDFAを構築する"
  (let* ((nfa-trans (get-nfa-transitions))
         (dfa-states-hash (make-hash-table :test 'equal))
         (state-list (make-array $max-dfa-states :fill-pointer 0))
         (dfa-trans-table (make-array (list $max-dfa-states $num-tile-transitions) :initial-element nil))
         (start-set (list 0)))
    (setf (gethash start-set dfa-states-hash) 0)
    (vector-push start-set state-list)
    (let ((head-index 0))
      (do () ((>= head-index (length state-list)))
        (let* ((curr-set (aref state-list head-index))
               (curr-id head-index))
          (iterate ((tiles (scan-range :from 0 :below $num-tile-transitions)))
            (let ((next-set nil))
              (iterate ((st (scan 'list curr-set)))
                (iterate ((nxt (scan 'list (aref nfa-trans st tiles))))
                  (pushnew nxt next-set)))
              (setf next-set (sort next-set #'<))
              (let ((next-id (gethash next-set dfa-states-hash)))
                (unless next-id
                  (setf next-id (length state-list))
                  (setf (gethash next-set dfa-states-hash) next-id)
                  (vector-push next-set state-list))
                (setf (aref dfa-trans-table curr-id tiles) next-id))))
          (incf head-index))))
    (values state-list dfa-trans-table)))

(defun minimize-dfa (state-list dfa-trans-table)
  "DFAを最小化する"
  (let* ((num-states (length state-list))
         (group-array (make-fixnum-array num-states))
         (accept-p0 (make-array num-states :initial-element nil))
         (accept-p1 (make-array num-states :initial-element nil)))
    (iterate ((index-i (scan-range :from 0 :below num-states)))
      (let ((st (aref state-list index-i)))
        (setf (aref accept-p0 index-i) (if (member 0 st) t nil))
        (setf (aref accept-p1 index-i) (if (member 1 st) t nil))
        (setf (aref group-array index-i) (+ (if (aref accept-p0 index-i) 1 0)
                                            (if (aref accept-p1 index-i) 2 0)))))
    (let ((is-changed t))
      (do () ((not is-changed))
        (setf is-changed nil)
        (let ((signature-hash (make-hash-table :test 'equal))
              (new-groups (make-fixnum-array num-states))
              (next-group-id 0))
          (iterate ((index-i (scan-range :from 0 :below num-states)))
            (let ((sig (list (aref group-array index-i))))
              (iterate ((tiles (scan-range :from 0 :below $num-tile-transitions)))
                (let ((nxt (aref dfa-trans-table index-i tiles)))
                  (push (if nxt (aref group-array nxt) -1) sig)))
              (let ((gid (gethash sig signature-hash)))
                (unless gid
                  (setf gid next-group-id)
                  (incf next-group-id)
                  (setf (gethash sig signature-hash) gid))
                (setf (aref new-groups index-i) gid))))
          (iterate ((index-i (scan-range :from 0 :below num-states)))
            (when (/= (aref group-array index-i) (aref new-groups index-i))
              (setf is-changed t)))
          (setf group-array new-groups))))
    
    (let ((num-groups 0))
      (iterate ((grp (scan 'vector group-array)))
        (setf num-groups (max num-groups grp)))
      (incf num-groups)
      (let* ((min-trans (make-array (list num-groups $num-tile-transitions) :element-type 'fixnum :initial-element 0))
             (min-acc-p0 (make-array num-groups :initial-element nil))
             (min-acc-p1 (make-array num-groups :initial-element nil))
             (start-group (aref group-array 0)))
        (iterate ((index-i (scan-range :from 0 :below num-states)))
          (let ((grp (aref group-array index-i)))
            (setf (aref min-acc-p0 grp) (aref accept-p0 index-i))
            (setf (aref min-acc-p1 grp) (aref accept-p1 index-i))
            (iterate ((tiles (scan-range :from 0 :below $num-tile-transitions)))
              (setf (aref min-trans grp tiles) 
                    (if (aref dfa-trans-table index-i tiles)
                        (aref group-array (aref dfa-trans-table index-i tiles))
                        -1)))))
        (values num-groups min-trans min-acc-p0 min-acc-p1 start-group)))))

(defun matrix-mul (matrix1 matrix2 size-n)
  "1次元に平坦化された多項式行列のスパース乗算"
  (declare (type (simple-array fixnum (*)) matrix1 matrix2))
  (let* ((array-len (* size-n size-n $max-tiles-per-suit))
         (result-mat (make-fixnum-array array-len)))
    (iterate ((index-i (scan-range :from 0 :below size-n)))
      (let ((i-offset (* index-i size-n)))
        (iterate ((index-k (scan-range :from 0 :below size-n)))
          (let ((ik-offset (* (+ i-offset index-k) $max-tiles-per-suit))
                (k-offset (* index-k size-n)))
            (iterate ((deg1 (scan-range :from 0 :below $max-tiles-per-suit)))
              (let ((val1 (aref matrix1 (+ ik-offset deg1))))
                (when (> val1 0)
                  (iterate ((index-j (scan-range :from 0 :below size-n)))
                    (let ((ij-offset (* (+ i-offset index-j) $max-tiles-per-suit))
                          (kj-offset (* (+ k-offset index-j) $max-tiles-per-suit)))
                      (iterate ((deg2 (scan-range :from 0 :below (- $max-tiles-per-suit deg1))))
                        (let ((val2 (aref matrix2 (+ kj-offset deg2))))
                          (when (> val2 0)
                            (let ((idx (+ ij-offset deg1 deg2)))
                              (setf (aref result-mat idx)
                                    (mod (+ (aref result-mat idx) (* val1 val2)) $const-modulo)))))))))))))))
    result-mat))

(defun matrix-pow (base-mat power-val size-n)
  "ダブリングによる行列の累乗"
  (let* ((array-len (* size-n size-n $max-tiles-per-suit))
         (result-mat (make-fixnum-array array-len)))
    (iterate ((index-i (scan-range :from 0 :below size-n)))
      (setf (aref result-mat (+ (* (+ (* index-i size-n) index-i) $max-tiles-per-suit) 0)) 1))
    (let ((current-base base-mat)
          (current-exp power-val))
      (do () ((<= current-exp 0))
        (when (oddp current-exp) 
          (setf result-mat (matrix-mul result-mat current-base size-n)))
        (setf current-base (matrix-mul current-base current-base size-n))
        (setf current-exp (ash current-exp -1)))
      result-mat)))

(defun poly-mul-t (poly1 poly2 limit-t)
  "上限付き多項式の乗算"
  (declare (type (simple-array fixnum (*)) poly1 poly2))
  (let ((result-poly (make-fixnum-array (1+ limit-t))))
    (iterate ((deg1 (scan-range :from 0 :upto limit-t)))
      (let ((val1 (aref poly1 deg1)))
        (when (> val1 0)
          (iterate ((deg2 (scan-range :from 0 :upto (- limit-t deg1))))
            (let ((val2 (aref poly2 deg2)))
              (when (> val2 0)
                (setf (aref result-poly (+ deg1 deg2))
                      (mod (+ (aref result-poly (+ deg1 deg2)) (* val1 val2)) $const-modulo))))))))
    result-poly))

(defun poly-pow-t (base-poly power-val limit-t)
  "上限付き多項式の累乗"
  (let ((result-poly (make-fixnum-array (1+ limit-t))))
    (setf (aref result-poly 0) 1)
    (let ((current-base base-poly)
          (current-exp power-val))
      (do () ((<= current-exp 0))
        (when (oddp current-exp) 
          (setf result-poly (poly-mul-t result-poly current-base limit-t)))
        (setf current-base (poly-mul-t current-base current-base limit-t))
        (setf current-exp (ash current-exp -1)))
      result-poly)))

(defun solve (&optional (limit-n #.(expt 10 8)) (limit-s #.(expt 10 8)) (limit-t 30))
  (multiple-value-bind (state-list dfa-trans-table) (build-dfa)
    (multiple-value-bind (min-num-states min-trans min-acc-p0 min-acc-p1 start-group)
                         (minimize-dfa state-list dfa-trans-table)
      (format t "観測: DFA NFA States = ~D, Minimized DFA = ~D~%" (length state-list) min-num-states)
      
      (let* ((array-len (* min-num-states min-num-states $max-tiles-per-suit))
             (adj-matrix (make-fixnum-array array-len)))
        (iterate ((index-i (scan-range :from 0 :below min-num-states)))
          (iterate ((tiles (scan-range :from 0 :below $num-tile-transitions)))
            (let ((nxt (aref min-trans index-i tiles)))
              (when (>= nxt 0)
                (let ((idx (+ (* (+ (* index-i min-num-states) nxt) $max-tiles-per-suit) tiles)))
                  (incf (aref adj-matrix idx)))))))
                  
        (let ((matrix-powered (matrix-pow adj-matrix limit-n min-num-states))
              (poly-no-pair (make-fixnum-array $max-tiles-per-suit))
              (poly-with-pair (make-fixnum-array $max-tiles-per-suit)))
          
          (iterate ((index-j (scan-range :from 0 :below min-num-states)))
            (let ((ij-offset (* (+ (* start-group min-num-states) index-j) $max-tiles-per-suit)))
              (when (aref min-acc-p0 index-j)
                (iterate ((deg (scan-range :from 0 :below $max-tiles-per-suit)))
                  (setf (aref poly-no-pair deg) 
                        (mod (+ (aref poly-no-pair deg) (aref matrix-powered (+ ij-offset deg))) $const-modulo))))
              (when (aref min-acc-p1 index-j)
                (iterate ((deg (scan-range :from 0 :below $max-tiles-per-suit)))
                  (setf (aref poly-with-pair deg) 
                        (mod (+ (aref poly-with-pair deg) (aref matrix-powered (+ ij-offset deg))) $const-modulo))))))
              
          (let ((suits-no-pair (make-fixnum-array (1+ limit-t)))
                (suits-with-pair (make-fixnum-array (1+ limit-t))))
            (iterate ((index-j (scan-range :from 0 :upto limit-t)))
              (let ((idx-p (* 3 index-j)))
                (when (< idx-p $max-tiles-per-suit) (setf (aref suits-no-pair index-j) (aref poly-no-pair idx-p))))
              (let ((idx-q (+ (* 3 index-j) 2)))
                (when (< idx-q $max-tiles-per-suit) (setf (aref suits-with-pair index-j) (aref poly-with-pair idx-q)))))
                
            (let* ((pow-no-pair (poly-pow-t suits-no-pair (1- limit-s) limit-t))
                   (total-combinations (poly-mul-t suits-with-pair pow-no-pair limit-t))
                   (final-answer (mod (* (mod limit-s $const-modulo) (aref total-combinations limit-t)) $const-modulo)))
              (format t "w(~D, ~D, ~D) = ~D~%" limit-n limit-s limit-t final-answer)
              final-answer)))))))

#+| Do it | (project-euler-0696:solve)
#|------------------------------------------------------------|
Timing the evaluation of (solve)
観測: DFA NFA States = 68, Minimized DFA = 56
w(100000000, 100000000, 30) = 436944244

User time    =       25.312
System time  =        0.120
Elapsed time =       25.318
Allocation   = 95988016 bytes
8458 Page faults
GC time      =        0.012
 |------------------------------------------------------------|#
;;→ 436944244
:ok