;;; -*- mode: Lisp; coding: utf-8  -*-
;;; llm-model: gemini-3-flash-preview
(cl:in-package cl-user)
(defpackage #:project-euler-0356 (:use cl iterate alexandria) (:export #:solve))
(in-package #:project-euler-0356)

#||
(cl:comment "PE 356 Mathematical Constraints and Shortcuts")
(cl:comment "Invariant 1: The roots of g(x) = x^3 - 2^n x^2 + n = 0 are a_n (largest), b_n, and c_n.")
(cl:comment "Invariant 2: For n >= 1, the other two roots b_n and c_n satisfy 0 < b_n < 1 and -1 < c_n < 0, and |c_n| < b_n.")
(cl:comment "Constraint 1: Since k = 987654321 is odd, 0 < b_n^k + c_n^k < 1.")
(cl:comment "Constraint 2: The sum of k-th powers S_k = a_n^k + b_n^k + c_n^k is an integer, generated by the linear recurrence S_k = 2^n S_{k-1} - n S_{k-3}.")
(cl:comment "Shortcut: a_n^k = S_k - (b_n^k + c_n^k), and since 0 < b_n^k + c_n^k < 1, we strictly have floor(a_n^k) = S_k - 1.")
(forall (n k)
  (implies (and (>= n 1) (is-odd k))
           (= (floor (expt a_n k)) (- (S k n) 1))))
||#


(defun power-mod (base exp modulo)
  "Calculates (base^exp) mod modulo efficiently."
  (let ((result 1)
        (current-base (mod base modulo)))
    (iterate (while (> exp 0))
      (when (oddp exp)
        (setq result (mod (* result current-base) modulo)))
      (setq current-base (mod (* current-base current-base) modulo))
      (setq exp (ash exp -1)))
    result))

(defun multiply-matrices (matrix-a matrix-b modulo)
  "Multiplies two 3x3 matrices under a modulo."
  (let ((matrix-c (make-array '(3 3) :element-type 'integer :initial-element 0)))
    (iterate (for i from 0 to 2)
      (iterate (for j from 0 to 2)
        (let ((sum 0))
          (iterate (for k from 0 to 2)
            (incf sum (* (aref matrix-a i k) (aref matrix-b k j))))
          (setf (aref matrix-c i j) (mod sum modulo)))))
    matrix-c))

(defun power-matrix (matrix-a exp modulo)
  "Raises a 3x3 matrix to a given power under a modulo using exponentiation by squaring."
  (let ((result-matrix (make-array '(3 3) :element-type 'integer :initial-contents '((1 0 0) (0 1 0) (0 0 1))))
        (base-matrix matrix-a))
    (iterate (while (> exp 0))
      (when (oddp exp)
        (setq result-matrix (multiply-matrices result-matrix base-matrix modulo)))
      (setq base-matrix (multiply-matrices base-matrix base-matrix modulo))
      (setq exp (ash exp -1)))
    result-matrix))

(defun build-transition-matrix (n modulo)
  "Builds the transition matrix for the Newton's sums recurrence S_m = 2^n * S_{m-1} - n * S_{m-3}.
   State vector is [S_m, S_{m-1}, S_{m-2}]^T."
  (let ((transition-matrix (make-array '(3 3) :element-type 'integer :initial-element 0))
        (two-to-n (power-mod 2 n modulo))
        (minus-n (mod (- n) modulo)))
    (setf (aref transition-matrix 0 0) two-to-n)
    (setf (aref transition-matrix 0 1) 0)
    (setf (aref transition-matrix 0 2) minus-n)
    (setf (aref transition-matrix 1 0) 1)
    (setf (aref transition-matrix 2 1) 1)
    transition-matrix))

(defun multiply-matrix-vector (matrix-m vector-v modulo)
  "Multiplies a 3x3 matrix by a 3x1 vector under a modulo."
  (let ((result-vector (make-array 3 :element-type 'integer :initial-element 0)))
    (iterate (for i from 0 to 2)
      (let ((sum 0))
        (iterate (for j from 0 to 2)
          (incf sum (* (aref matrix-m i j) (aref vector-v j))))
        (setf (aref result-vector i) (mod sum modulo))))
    result-vector))

(defun solve ()
  (let ((modulo 100000000)
        (power-k 987654321)
        (total-sum 0))
    (iterate (for n from 1 to 30)
      (let* ((transition-matrix (build-transition-matrix n modulo))
             ;; We need S_k. Given initial vector V_2 = [S_2, S_1, S_0]^T, we apply matrix k-2 times.
             (matrix-pow (power-matrix transition-matrix (- power-k 2) modulo))
             
             ;; Calculate initial values S_0, S_1, S_2.
             (s-2 (power-mod 2 (* 2 n) modulo))
             (s-1 (power-mod 2 n modulo))
             (s-0 3)
             (vector-v (make-array 3 :element-type 'integer :initial-contents (list s-2 s-1 s-0)))
             
             ;; Compute V_k = M^(k-2) * V_2
             (vector-result (multiply-matrix-vector matrix-pow vector-v modulo))
             (s-k (aref vector-result 0))
             
             ;; Apply the mathematical shortcut: floor(a_n^k) = S_k - 1.
             ;; Modulo operation ensures safe subtraction.
             (floor-a-k (mod (- s-k 1) modulo)))
             
        (format t "n = ~2D: S_k = ~8,'0D, floor(a_n^k) = ~8,'0D~%" n s-k floor-a-k)
        (incf total-sum floor-a-k)))
        
    (let ((final-answer (mod total-sum modulo)))
      (format t "Final Sum Modulo 10^8: ~8,'0D~%" final-answer)
      final-answer)))


#+| Do it | (solve )
#|------------------------------------------------------------|
Timing the evaluation of (solve)
n =  1: S_k = 24098477, floor(a_n^k) = 24098476
n =  2: S_k = 76228864, floor(a_n^k) = 76228863
n =  3: S_k = 85565263, floor(a_n^k) = 85565262
n =  4: S_k = 23352576, floor(a_n^k) = 23352575
n =  5: S_k = 75789737, floor(a_n^k) = 75789736
n =  6: S_k = 96987904, floor(a_n^k) = 96987903
n =  7: S_k = 02567611, floor(a_n^k) = 02567610
n =  8: S_k = 22528256, floor(a_n^k) = 22528255
n =  9: S_k = 58445877, floor(a_n^k) = 58445876
n = 10: S_k = 23595264, floor(a_n^k) = 23595263
n = 11: S_k = 32693703, floor(a_n^k) = 32693702
n = 12: S_k = 96842496, floor(a_n^k) = 96842495
n = 13: S_k = 47252769, floor(a_n^k) = 47252768
n = 14: S_k = 44759808, floor(a_n^k) = 44759807
n = 15: S_k = 94813683, floor(a_n^k) = 94813682
n = 16: S_k = 16131072, floor(a_n^k) = 16131071
n = 17: S_k = 94343917, floor(a_n^k) = 94343916
n = 18: S_k = 95257344, floor(a_n^k) = 95257343
n = 19: S_k = 81897663, floor(a_n^k) = 81897662
n = 20: S_k = 75257856, floor(a_n^k) = 75257855
n = 21: S_k = 58429977, floor(a_n^k) = 58429976
n = 22: S_k = 40884224, floor(a_n^k) = 40884223
n = 23: S_k = 00821163, floor(a_n^k) = 00821162
n = 24: S_k = 49970176, floor(a_n^k) = 49970175
n = 25: S_k = 48049957, floor(a_n^k) = 48049956
n = 26: S_k = 38440704, floor(a_n^k) = 38440703
n = 27: S_k = 83170871, floor(a_n^k) = 83170870
n = 28: S_k = 36508416, floor(a_n^k) = 36508415
n = 29: S_k = 16796817, floor(a_n^k) = 16796816
n = 30: S_k = 86527744, floor(a_n^k) = 86527743
Final Sum Modulo 10^8: 28010159

User time    =        0.003
System time  =        0.000
Elapsed time =        0.002
Allocation   = 4295158056 bytes
120 Page faults
GC time      =        0.000
 |------------------------------------------------------------|#
;;→ 28010159
:ok