;;; -*- mode: Lisp; coding: utf-8  -*-
;;; llm-model: gemini-3-flash-preview
(cl:in-package cl-user)
(defpackage #:project-euler-0821 (:use cl iterate alexandria) (:export #:solve))
(in-package #:project-euler-0821)

(defmacro optimized-code-p (boole)
  (typecase boole
    (null nil)
    (T `(declaim (optimize (speed 3) (safety 0) (debug 0))))))

(optimized-code-p T)

(declaim (inline count-coprime-to-6))
(defun count-coprime-to-6 (m)
  "1からmまでの整数のうち、2でも3でも割り切れないものの個数"
  (declare (type (unsigned-byte 64) m))
  (let ((q (truncate m 6))
        (r (rem m 6)))
    (+ (* 2 q)
       (cond ((= r 0) 0)
             ((<= r 4) 1)
             (t 2)))))

(defvar *f-cache* (make-hash-table))

(defun get-grid-data (K)
  (let ((pts nil))
    (iterate (for b from 0)
      (let ((p3 (expt 3 b)))
        (if (> p3 K) (finish))
        (iterate (for a from 0)
          (let ((p2 (expt 2 a)))
            (if (> (* p2 p3) K) (finish))
            (push (cons a b) pts)))))
    (let* ((sorted-pts (coerce (sort pts (lambda (p1 p2)
                                           (if (= (cdr p1) (cdr p2))
                                               (< (car p1) (car p2))
                                               (< (cdr p1) (cdr p2)))))
                               'simple-vector))
           (n (length sorted-pts))
           (pt-map (make-hash-table :test 'equal)))
      (iterate (for i from 0 below n)
        (setf (gethash (aref sorted-pts i) pt-map) i))
      (values sorted-pts n pt-map))))

(defun compute-f (K)
  "グリッド Ω_K における最大重みパッキングを計算"
  (declare (type (unsigned-byte 64) K))
  (if (gethash K *f-cache*) (return-from compute-f (gethash K *f-cache*)))
  (multiple-value-bind (pts n pt-map) (get-grid-data K)
    (let ((memo (make-hash-table :test 'equal)))
      (labels ((rec (idx mask)
                 (if (>= idx n) 0
                     (let ((state (cons idx mask)))
                       (or (gethash state memo)
                           (setf (gethash state memo)
                                 (if (logbitp 0 mask)
                                     (rec (1+ idx) (ash mask -1))
                                     (let* ((p (aref pts idx))
                                            (a (car p)) (b (cdr p))
                                            ;; 1. (a,b) を S に入れない場合
                                            (res (rec (1+ idx) (ash mask -1)))
                                            ;; 2. (a,b) を S に入れる場合 (Lトロミノ配置)
                                            (w 1)
                                            (new-mask (ash mask -1))
                                            (idx-r (gethash (cons (1+ a) b) pt-map))
                                            (idx-u (gethash (cons a (1+ b)) pt-map)))
                                       (when (and idx-r (not (logbitp (1- (- idx-r idx)) new-mask)))
                                         (incf w)
                                         (setf new-mask (logior new-mask (ash 1 (1- (- idx-r idx))))))
                                       (when (and idx-u (not (logbitp (1- (- idx-u idx)) new-mask)))
                                         (incf w)
                                         (setf new-mask (logior new-mask (ash 1 (1- (- idx-u idx))))))
                                       (max res (+ w (rec (1+ idx) new-mask)))))))))))
        (let ((result (rec 0 0)))
          (setf (gethash K *f-cache*) result)
          result)))))

(defun solve (&optional (n 10000000000000000))
  (declare (type (unsigned-byte 64) n))
  (format t "Phase 1: Identifying ~A unique grid shapes...~%" 935)
  (let ((ks nil))
    (iterate (for i from 0 to 60)
      (let ((p2 (expt 2 i)))
        (if (> p2 n) (finish))
        (iterate (for j from 0 to 40)
          (let ((p3 (expt 3 j)))
            (let ((val (* p2 p3)))
              (if (<= val n) 
                  (push (truncate n val) ks) 
                  (finish)))))))
    (setf ks (sort (remove-duplicates ks) #'<))
    
    (format t "Phase 2: Summing optimal solutions for each K...~%")
    (let ((ans 0)
          (prev-k 0))
      (declare (type (unsigned-byte 64) ans prev-k))
      (iterate (for k in ks)
        (let ((count (- (count-coprime-to-6 k) (count-coprime-to-6 prev-k))))
          (incf ans (* count (compute-f k)))
          (setf prev-k k)))
      
      (format t "F(6) = ~A (expected 5)~%" (let ((*f-cache* (make-hash-table))) (solve 6)))
      (format t "F(20) = ~A (expected 19)~%" (let ((*f-cache* (make-hash-table))) (solve 20)))
      (format t "Result: F(~A) = ~A~%" n ans)
      ans)))