;;; -*- mode: Lisp; coding: utf-8  -*-
;;; llm-model: gemini-3.1-pro
(cl:in-package cl-user)
(defpackage #:project-euler-0851 (:use cl iterate alexandria) (:export #:solve))
(in-package #:project-euler-0851)

(defmacro optimized-code-p (boole)
  (typecase boole
    (null nil)
    (T `(declaim (optimize (speed 3) (safety 0) (debug 0))))))

(optimized-code-p T)


(defconstant $limit-10000 10000)
(defconstant $modulo-prime (+ #.(expt 10 9) 7))
(defconstant $matrix-size 22)

(defun exact-sigma-m (k-val target-m)
  (let ((sum-val 0))
    (iterate (for i-idx from 1 to target-m)
      (if (= (mod target-m i-idx) 0)
          (incf sum-val (expt i-idx k-val))))
    sum-val))

(defun compute-exact-s (limit-n)
  (let ((s-poly (make-array (1+ limit-n) :initial-element 0)))
    (iterate (for i-idx from 1 to limit-n)
      (setf (aref s-poly i-idx) (exact-sigma-m 1 i-idx)))
    s-poly))

(defun poly-mul (a-poly b-poly limit-n)
  (let ((c-poly (make-array (1+ limit-n) :initial-element 0)))
    (iterate (for i-idx from 0 to limit-n)
      (iterate (for j-idx from 0 to (- limit-n i-idx))
        (incf (aref c-poly (+ i-idx j-idx)) (* (aref a-poly i-idx) (aref b-poly j-idx)))))
    c-poly))

(defun compute-exact-tau (limit-n)
  (let ((tau-array (make-array (1+ limit-n) :initial-element 0))
        (sigma1-array (make-array (1+ limit-n) :initial-element 0)))
    (iterate (for i-idx from 1 to limit-n)
      (iterate (for j-idx from i-idx to limit-n by i-idx)
        (incf (aref sigma1-array j-idx) i-idx)))
    (setf (aref tau-array 1) 1)
    (iterate (for n-idx from 2 to limit-n)
      (let ((sum-val 0))
        (iterate (for k-idx from 1 to (- n-idx 1))
          (incf sum-val (* (aref sigma1-array (- n-idx k-idx)) (aref tau-array k-idx))))
        (setf (aref tau-array n-idx) (/ (* -24 sum-val) (- n-idx 1)))))
    tau-array))

(defun build-matrix-and-vector (limit-size)
  (let ((a-mat (make-array (list limit-size limit-size) :initial-element 0))
        (v-vec (make-array limit-size :initial-element 0))
        (s-poly (compute-exact-s limit-size)))
    (let* ((s2-poly (poly-mul s-poly s-poly limit-size))
           (s3-poly (poly-mul s2-poly s-poly limit-size))
           (s6-poly (poly-mul s3-poly s3-poly limit-size)))
      (iterate (for i-idx from 0 to (- limit-size 1))
        (setf (aref v-vec i-idx) (* 64 (aref s6-poly (+ i-idx 1))))))
    (iterate (for i-idx from 0 to (- limit-size 1))
      (let ((m-val (+ i-idx 1)))
        (setf (aref a-mat i-idx 0) (exact-sigma-m 1 m-val))
        (setf (aref a-mat i-idx 1) (exact-sigma-m 3 m-val))
        (setf (aref a-mat i-idx 2) (* m-val (exact-sigma-m 1 m-val)))
        (setf (aref a-mat i-idx 3) (exact-sigma-m 5 m-val))
        (setf (aref a-mat i-idx 4) (* m-val (exact-sigma-m 3 m-val)))
        (setf (aref a-mat i-idx 5) (* m-val m-val (exact-sigma-m 1 m-val)))
        (setf (aref a-mat i-idx 6) (exact-sigma-m 7 m-val))
        (setf (aref a-mat i-idx 7) (* m-val (exact-sigma-m 5 m-val)))
        (setf (aref a-mat i-idx 8) (* m-val m-val (exact-sigma-m 3 m-val)))
        (setf (aref a-mat i-idx 9) (* m-val m-val m-val (exact-sigma-m 1 m-val)))
        (setf (aref a-mat i-idx 10) (exact-sigma-m 9 m-val))
        (setf (aref a-mat i-idx 11) (* m-val (exact-sigma-m 7 m-val)))
        (setf (aref a-mat i-idx 12) (* m-val m-val (exact-sigma-m 5 m-val)))
        (setf (aref a-mat i-idx 13) (* m-val m-val m-val (exact-sigma-m 3 m-val)))
        (setf (aref a-mat i-idx 14) (* m-val m-val m-val m-val (exact-sigma-m 1 m-val)))
        (setf (aref a-mat i-idx 15) (exact-sigma-m 11 m-val))
        (setf (aref a-mat i-idx 16) (aref (compute-exact-tau limit-size) m-val))
        (setf (aref a-mat i-idx 17) (* m-val (exact-sigma-m 9 m-val)))
        (setf (aref a-mat i-idx 18) (* m-val m-val (exact-sigma-m 7 m-val)))
        (setf (aref a-mat i-idx 19) (* m-val m-val m-val (exact-sigma-m 5 m-val)))
        (setf (aref a-mat i-idx 20) (* m-val m-val m-val m-val (exact-sigma-m 3 m-val)))
        (setf (aref a-mat i-idx 21) (* m-val m-val m-val m-val m-val (exact-sigma-m 1 m-val)))))
    (values a-mat v-vec)))

(defun solve-linear-system (a-mat v-vec limit-size)
  (let ((m-mat (make-array (list limit-size (1+ limit-size)) :initial-element 0)))
    (iterate (for i-idx from 0 to (- limit-size 1))
      (iterate (for j-idx from 0 to (- limit-size 1))
        (setf (aref m-mat i-idx j-idx) (aref a-mat i-idx j-idx)))
      (setf (aref m-mat i-idx limit-size) (aref v-vec i-idx)))
    (iterate (for i-idx from 0 to (- limit-size 1))
      (let ((pivot-idx i-idx))
        (iterate (for j-idx from i-idx to (- limit-size 1))
          (when (not (= (aref m-mat j-idx i-idx) 0))
            (setf pivot-idx j-idx)
            (return)))
        (unless (= pivot-idx i-idx)
          (iterate (for j-idx from 0 to limit-size)
            (let ((temp (aref m-mat i-idx j-idx)))
              (setf (aref m-mat i-idx j-idx) (aref m-mat pivot-idx j-idx))
              (setf (aref m-mat pivot-idx j-idx) temp))))
        (let ((pivot-val (aref m-mat i-idx i-idx)))
          (iterate (for j-idx from (+ i-idx 1) to (- limit-size 1))
            (let ((factor-val (/ (aref m-mat j-idx i-idx) pivot-val)))
              (iterate (for k-idx from i-idx to limit-size)
                (decf (aref m-mat j-idx k-idx) (* factor-val (aref m-mat i-idx k-idx)))))))))
    (let ((c-vec (make-array limit-size :initial-element 0)))
      (iterate (for i-idx from (- limit-size 1) downto 0)
        (let ((sum-val 0))
          (iterate (for j-idx from (+ i-idx 1) to (- limit-size 1))
            (incf sum-val (* (aref m-mat i-idx j-idx) (aref c-vec j-idx))))
          (setf (aref c-vec i-idx) (/ (- (aref m-mat i-idx limit-size) sum-val) (aref m-mat i-idx i-idx)))))
      c-vec)))

(defun mod-inverse (value modulo-p)
  (let ((m0-val modulo-p) (y-val 0) (x-val 1) (a-val value) (p-val modulo-p))
    (if (= p-val 1)
        (return-from mod-inverse 0))
    (iterate (while (> a-val 1))
      (let ((q-val (floor a-val p-val))
            (t1-val p-val))
        (setf p-val (mod a-val p-val)
              a-val t1-val
              t1-val y-val)
        (setf y-val (- x-val (* q-val y-val))
              x-val t1-val)))
    (if (< x-val 0)
        (incf x-val m0-val))
    x-val))

(defun rational-mod (r-val modulo-p)
  (let* ((num-val (numerator r-val))
         (den-val (denominator r-val))
         (num-mod (mod num-val modulo-p))
         (den-mod (mod den-val modulo-p)))
    (mod (* num-mod (mod-inverse den-mod modulo-p)) modulo-p)))

(defun expt-mod (base-val exp-val modulo-p)
  (let ((res-val 1)
        (b-val (mod base-val modulo-p))
        (e-val exp-val))
    (iterate (while (> e-val 0))
      (if (oddp e-val)
          (setf res-val (mod (* res-val b-val) modulo-p)))
      (setf b-val (mod (* b-val b-val) modulo-p))
      (setf e-val (ash e-val -1)))
    res-val))

(defun prime-p (n-val)
  (if (< n-val 2) (return-from prime-p nil))
  (if (= n-val 2) (return-from prime-p t))
  (if (evenp n-val) (return-from prime-p nil))
  (iterate (for i-idx from 3 to (isqrt n-val) by 2)
    (if (= (mod n-val i-idx) 0) (return-from prime-p nil)))
  t)

(defun compute-m0 (limit-n modulo-p)
  (let ((res-val 1))
    (iterate (for i-idx from 1 to limit-n)
      (setf res-val (mod (* res-val i-idx) modulo-p)))
    res-val))

(defun compute-sigma-k-m (k-val limit-n modulo-p)
  (let ((res-val 1))
    (iterate (for pr from 2 to limit-n)
      (when (prime-p pr)
        (let ((e-val 0) (temp-val limit-n))
          (iterate (while (>= temp-val pr))
            (setf temp-val (floor temp-val pr))
            (incf e-val temp-val))
          (let ((term-val 0))
            (if (= k-val 1)
                (if (= (mod pr modulo-p) 1)
                    (setf term-val (mod (+ e-val 1) modulo-p))
                    (let ((pr-mod (mod pr modulo-p)))
                      (setf term-val (mod (* (- (mod (expt-mod pr-mod (+ e-val 1) modulo-p) modulo-p) 1)
                                             (mod-inverse (- pr-mod 1) modulo-p)) modulo-p))))
                (let ((pr-k (expt-mod (mod pr modulo-p) k-val modulo-p)))
                  (if (= pr-k 1)
                      (setf term-val (mod (+ e-val 1) modulo-p))
                      (setf term-val (mod (* (- (mod (expt-mod pr-k (+ e-val 1) modulo-p) modulo-p) 1)
                                             (mod-inverse (- pr-k 1) modulo-p)) modulo-p)))))
            (setf res-val (mod (* res-val term-val) modulo-p))))))
    res-val))

(defun compute-tau (limit-n modulo-p)
  (let ((tau-array (make-array (1+ limit-n) :initial-element 0))
        (sigma1-array (make-array (1+ limit-n) :initial-element 0)))
    (iterate (for i-idx from 1 to limit-n)
      (iterate (for j-idx from i-idx to limit-n by i-idx)
        (incf (aref sigma1-array j-idx) i-idx)))
    (iterate (for i-idx from 1 to limit-n)
      (setf (aref sigma1-array i-idx) (mod (aref sigma1-array i-idx) modulo-p)))
    (setf (aref tau-array 1) 1)
    (iterate (for n-idx from 2 to limit-n)
      (let ((sum-val 0))
        (iterate (for k-idx from 1 to (- n-idx 1))
          (let ((term (mod (* (aref sigma1-array (- n-idx k-idx)) (aref tau-array k-idx)) modulo-p)))
            (incf sum-val term)
            (when (>= sum-val modulo-p)
              (decf sum-val modulo-p))))
        (let* ((rhs (mod (* -24 sum-val) modulo-p))
               (inv (mod-inverse (- n-idx 1) modulo-p)))
          (setf (aref tau-array n-idx) (mod (* rhs inv) modulo-p)))))
    tau-array))

(defun compute-tau-m (limit-n tau-array modulo-p)
  (let ((res-val 1))
    (iterate (for pr from 2 to limit-n)
      (when (prime-p pr)
        (let ((e-val 0) (temp-val limit-n))
          (iterate (while (>= temp-val pr))
            (setf temp-val (floor temp-val pr))
            (incf e-val temp-val))
          (let ((t0-val 1)
                (t1-val (aref tau-array pr))
                (pr-11 (expt-mod pr 11 modulo-p))
                (tau-p (aref tau-array pr)))
            (cond
              ((= e-val 0) (setf res-val (mod (* res-val t0-val) modulo-p)))
              ((= e-val 1) (setf res-val (mod (* res-val t1-val) modulo-p)))
              (t
               (let ((cur-val 0))
                 (iterate (for i-idx from 2 to e-val)
                   (setf cur-val (mod (- (* tau-p t1-val) (* pr-11 t0-val)) modulo-p))
                   (setf t0-val t1-val)
                   (setf t1-val cur-val))
                 (setf res-val (mod (* res-val cur-val) modulo-p)))))))))
    res-val))

(defun solve ()
  (multiple-value-bind (a-mat v-vec) (build-matrix-and-vector $matrix-size)
    (let ((c-vec (solve-linear-system a-mat v-vec $matrix-size))
          (m0-val (compute-m0 $limit-10000 $modulo-prime))
          (sig1-val (compute-sigma-k-m 1 $limit-10000 $modulo-prime))
          (sig3-val (compute-sigma-k-m 3 $limit-10000 $modulo-prime))
          (sig5-val (compute-sigma-k-m 5 $limit-10000 $modulo-prime))
          (sig7-val (compute-sigma-k-m 7 $limit-10000 $modulo-prime))
          (sig9-val (compute-sigma-k-m 9 $limit-10000 $modulo-prime))
          (sig11-val (compute-sigma-k-m 11 $limit-10000 $modulo-prime))
          (tau-arr (compute-tau $limit-10000 $modulo-prime)))
      (let* ((taum-val (compute-tau-m $limit-10000 tau-arr $modulo-prime))
             (m0-2 (expt-mod m0-val 2 $modulo-prime))
             (m0-3 (expt-mod m0-val 3 $modulo-prime))
             (m0-4 (expt-mod m0-val 4 $modulo-prime))
             (m0-5 (expt-mod m0-val 5 $modulo-prime))
             (v-seq (make-array $matrix-size :initial-element 0)))
        
        (setf (aref v-seq 0) sig1-val)
        (setf (aref v-seq 1) sig3-val)
        (setf (aref v-seq 2) (mod (* m0-val sig1-val) $modulo-prime))
        (setf (aref v-seq 3) sig5-val)
        (setf (aref v-seq 4) (mod (* m0-val sig3-val) $modulo-prime))
        (setf (aref v-seq 5) (mod (* m0-2 sig1-val) $modulo-prime))
        (setf (aref v-seq 6) sig7-val)
        (setf (aref v-seq 7) (mod (* m0-val sig5-val) $modulo-prime))
        (setf (aref v-seq 8) (mod (* m0-2 sig3-val) $modulo-prime))
        (setf (aref v-seq 9) (mod (* m0-3 sig1-val) $modulo-prime))
        (setf (aref v-seq 10) sig9-val)
        (setf (aref v-seq 11) (mod (* m0-val sig7-val) $modulo-prime))
        (setf (aref v-seq 12) (mod (* m0-2 sig5-val) $modulo-prime))
        (setf (aref v-seq 13) (mod (* m0-3 sig3-val) $modulo-prime))
        (setf (aref v-seq 14) (mod (* m0-4 sig1-val) $modulo-prime))
        (setf (aref v-seq 15) sig11-val)
        (setf (aref v-seq 16) taum-val)
        (setf (aref v-seq 17) (mod (* m0-val sig9-val) $modulo-prime))
        (setf (aref v-seq 18) (mod (* m0-2 sig7-val) $modulo-prime))
        (setf (aref v-seq 19) (mod (* m0-3 sig5-val) $modulo-prime))
        (setf (aref v-seq 20) (mod (* m0-4 sig3-val) $modulo-prime))
        (setf (aref v-seq 21) (mod (* m0-5 sig1-val) $modulo-prime))
        
        (format t "[DEBUG] M0 = ~A~%" m0-val)
        (format t "[DEBUG] tau(M0) = ~A~%" taum-val)
        
        (let ((ans-val 0))
          (iterate (for i-idx from 0 to (- $matrix-size 1))
            (let ((c-mod (rational-mod (aref c-vec i-idx) $modulo-prime)))
              (incf ans-val (mod (* c-mod (aref v-seq i-idx)) $modulo-prime))
              (setf ans-val (mod ans-val $modulo-prime))))
          ans-val)))))


#+| Do it | (solve )
#|------------------------------------------------------------|
Timing the evaluation of (solve)
[DEBUG] M0 = 531950728
[DEBUG] tau(M0) = 145181373

User time    =        1.272
System time  =        0.015
Elapsed time =        1.235
Allocation   = 308480 bytes
403 Page faults
GC time      =        0.001
 |------------------------------------------------------------|#
;;→ 726358482
:ok