;;; -*- mode: Lisp; coding: utf-8  -*-
;;; llm-model: gemini-3.1-pro
(cl:in-package cl-user)
(defpackage #:project-euler-0404 (:use cl iterate alexandria) (:export #:solve))
(in-package #:project-euler-0404)

#||
(cl:comment "Project Euler 404: Canonical ellipsoidal triplets")
(cl:comment "Ellipses E_a and rotated E_a' intersect. Distances b and c satisfy 1/b^2 + 1/c^2 = 5/(4a^2) with c < 2b.")
(cl:comment "Using Gaussian integers, primitive Pythagorean-like triples B^2 + C^2 = 5d^2 are generated by (2+i)(x+iy)^2.")
(cl:comment "Thus, B = |2x^2 - 2y^2 - 2xy| and C = |x^2 - y^2 + 4xy|.")
(cl:comment "Valid pairs must satisfy x > 0, y > 0, gcd(x, y) = 1, x != y (mod 2).")
(cl:comment "The geometry constraints partition the solution space strictly into two intervals for y/x:")
(cl:comment "Interval 1: 0 < y < x/3")
(cl:comment "Interval 2: x < y < 2x")
(cl:comment "If x + 2y == 0 (mod 5), the generated triplet is a 5x multiple of another primitive triplet, so we must exclude them.")
(cl:comment "For valid (x, y), the primitive a-value is a0 = B * C / 2.")
(cl:comment "For a given a0, there are floor(N / a0) multiples a <= N.")
(cl:comment "Since a0 grows as O(x^4), max x is around N^(1/4). For N=10^17, x <= 17782. Total loop iterations ~ 1.5 * 10^8.")
||#

(declaim (inline compute-a0))
(defun compute-a0 (x y)
  (let* ((x2 (* x x))
         (y2 (* y y))
         (xy (* x y))
         (b (abs (- (* 2 x2) (* 2 y2) (* 2 xy))))
         (c (abs (+ (- x2 y2) (* 4 xy)))))
    (ash (* b c) -1)))

(defun solve (&optional (limit 100000000000000000))
  (let ((ans 0))
    
    (format t "Starting Interval 1 (0 < y < x/3)...~%")
    (iterate (for x from 4)
      ;; y=1 のときが最小になるため、これで x の上限を検知して安全に離脱
      (let ((a0-min (compute-a0 x 1)))
        (when (> a0-min limit)
          (leave)))
      
      (iterate (for y from 1)
        (while (< (* 3 y) x))
        (when (and (oddp (- x y))
                   (= (gcd x y) 1)
                   (not (zerop (mod (+ x (* 2 y)) 5))))
          (let ((a0 (compute-a0 x y)))
            (when (<= a0 limit)
              (incf ans (truncate limit a0)))))))
              
    (format t "Starting Interval 2 (x < y < 2x)...~%")
    (iterate (for x from 1)
      ;; y=x+1 のときが最小になるため、これで x の上限を検知して安全に離脱
      (let ((a0-min (compute-a0 x (1+ x))))
        (when (> a0-min limit)
          (leave)))
      
      (iterate (for y from (1+ x))
        (while (< y (* 2 x)))
        (when (and (oddp (- y x))
                   (= (gcd x y) 1)
                   (not (zerop (mod (+ x (* 2 y)) 5))))
          (let ((a0 (compute-a0 x y)))
            (when (<= a0 limit)
              (incf ans (truncate limit a0)))))))
              
    (format t "Done.~%")
    ans))


#+| Do it | (solve )
#|------------------------------------------------------------|
Timing the evaluation of (solve)
Starting Interval 1 (0 < y < x/3)...
Starting Interval 2 (x < y < 2x)...
Done.

User time    =       14.555
System time  =        0.109
Elapsed time =       14.560
Allocation   = 2754672 bytes
3803 Page faults
GC time      =        0.000
 |------------------------------------------------------------|#
;;→ 1199215615081353
:ok