;;; -*- mode: Lisp; coding: utf-8  -*-
(cl:in-package cl-user)
(defpackage #:project-euler-0140 (:use cl alexandria))
(in-package #:project-euler-0140)

;; Problem 140: Golden Nuggets
;;
;; The problem defines an infinite polynomial series A_G(x) = x G_1 + x^2 G_2 + x^3 G_3 + ...
;; where G_k is a second-order recurrence relation G_k = G_{k-1} + G_{k-2}, with G_1 = 1 and G_2 = 4.
;; A "golden nugget" is a positive integer N such that A_G(x) = N for some rational x.
;; We need to find the sum of the first thirty golden nuggets.
;;
;; Step 1: Find the generating function for A_G(x).
;; Let A_G(x) = Sum_{k=1 to inf} G_k x^k.
;; Using the recurrence G_k = G_{k-1} + G_{k-2}:
;; A_G(x) = G_1 x + G_2 x^2 + Sum_{k=3 to inf} (G_{k-1} + G_{k-2}) x^k
;; A_G(x) = G_1 x + G_2 x^2 + x Sum_{j=2 to inf} G_j x^j + x^2 Sum_{j=1 to inf} G_j x^j
;; A_G(x) = G_1 x + G_2 x^2 + x (A_G(x) - G_1 x) + x^2 A_G(x)
;; Rearranging terms to solve for A_G(x):
;; A_G(x) (1 - x - x^2) = G_1 x + (G_2 - G_1) x^2
;; Given G_1 = 1 and G_2 = 4:
;; A_G(x) (1 - x - x^2) = 1x + (4-1)x^2
;; A_G(x) (1 - x - x^2) = x + 3x^2
;; Thus, A_G(x) = (x + 3x^2) / (1 - x - x^2).
;;
;; Step 2: Set A_G(x) = N (where N is a positive integer) and solve for x.
;; N = (x + 3x^2) / (1 - x - x^2)
;; N(1 - x - x^2) = x + 3x^2
;; N - Nx - Nx^2 = x + 3x^2
;; Rearranging into a quadratic equation in x:
;; (3+N)x^2 + (1+N)x - N = 0.
;;
;; Step 3: For x to be a rational number, the discriminant of this quadratic equation
;; must be a perfect square.
;; The discriminant D is given by b^2 - 4ac:
;; D = (1+N)^2 - 4(3+N)(-N)
;; D = (1+N)^2 + 4N(3+N)
;; D = 1 + 2N + N^2 + 12N + 4N^2
;; D = 5N^2 + 14N + 1.
;; For x to be rational, we require 5N^2 + 14N + 1 = k^2 for some non-negative integer k.
;; Since N is a positive integer (N >= 1), 5N^2 + 14N + 1 will always be positive, so k > 0.
;; Also, for x > 0 (which is required for A_G(x) to be a sum of positive terms),
;; we need k > 1+N, which is satisfied since 5N^2+14N+1 > (1+N)^2 for N >= 1.
;;
;; Step 4: Transform the equation 5N^2 + 14N + 1 = k^2 into a standard Pell-like equation.
;; Multiply the equation by 5:
;; 25N^2 + 70N + 5 = 5k^2
;; Complete the square for the N terms:
;; (5N)^2 + 2 * (5N) * 7 + 7^2 - 7^2 + 5 = 5k^2
;; (5N + 7)^2 - 49 + 5 = 5k^2
;; (5N + 7)^2 - 44 = 5k^2
;; Let Y = 5N + 7. The equation becomes:
;; Y^2 - 5k^2 = 44.
;;
;; We are looking for integer solutions (Y, k). Since Y = 5N + 7, Y must satisfy the congruence
;; Y = 7 (mod 5), which simplifies to Y = 2 (mod 5).
;;
;; Step 5: Find initial (fundamental) solutions (Y, k) for Y^2 - 5k^2 = 44.
;; By testing small integer values for N:
;; - If N=1: D = 5+14+1 = 20 (not a square)
;; - If N=2: D = 5(4)+14(2)+1 = 20+28+1 = 49 = 7^2. So k=7.
;;   Y = 5(2)+7 = 17. Thus, (Y,k) = (17,7) is a solution. (17^2 - 5*7^2 = 289 - 245 = 44).
;; - If N=3: D = 5(9)+14(3)+1 = 45+42+1 = 88 (not a square)
;; - If N=4: D = 5(16)+14(4)+1 = 80+56+1 = 137 (not a square)
;; - If N=5: D = 5(25)+14(5)+1 = 125+70+1 = 196 = 14^2. So k=14.
;;   Y = 5(5)+7 = 32. Thus, (Y,k) = (32,14) is another solution. (32^2 - 5*14^2 = 1024 - 980 = 44).
;;
;; These two solutions (17,7) and (32,14) serve as "seed" solutions for generating further golden nuggets.
;;
;; Step 6: Use the fundamental solution to the Pell equation p^2 - 5q^2 = 1 to generate more solutions.
;; The fundamental solution for p^2 - 5q^2 = 1 is (p,q) = (9,4) (since 9^2 - 5*4^2 = 81 - 80 = 1).
;;
;; Step 7: Solutions to Y^2 - 5k^2 = 44 are generated by (Y_j + k_j sqrt(5)) = (Y_0 + k_0 sqrt(5)) * (9 + 4 sqrt(5))^m.
;; Let's check the condition Y_j = 2 (mod 5).
;; The recurrence for Y_j is Y_{j+1} = 9Y_j + 5 * 4 * k_j = 9Y_j + 20k_j.
;; So, Y_{j+1} = 9Y_j (mod 5), which is Y_{j+1} = 4Y_j (mod 5).
;; For Y_0 = 17 = 2 (mod 5):
;; Y_1 = 4*2 = 8 = 3 (mod 5) - not valid
;; Y_2 = 4*3 = 12 = 2 (mod 5) - valid
;; This pattern shows that Y_j is valid (i.e., N is an integer) when m is an even number.
;; The same applies to the second family starting with Y_0' = 32 = 2 (mod 5).
;;
;; So, we only need to use the even powers of (9 + 4 sqrt(5)).
;; Let (p_F + q_F sqrt(5)) = (9 + 4 sqrt(5))^2 = 81 + 72 sqrt(5) + 16*5 = 161 + 72 sqrt(5).
;; So, the new recurrence relation for (Y, k) uses (p_F, q_F) = (161, 72):
;; Y_{new} = Y_old * p_F + 5 * k_old * q_F
;; k_{new} = Y_old * q_F + k_old * p_F
;;
;; We'll use two families of solutions:
;; Family A: Starts with (Y,k) = (17,7). Generates N = (Y-7)/5.
;; Family B: Starts with (Y,k) = (32,14). Generates N = (Y-7)/5.
;;
;; Step 8: Generate the first thirty golden nuggets and sum them.
;; Since each iteration (for j=0, 1, 2, ...) yields one nugget from Family A and one from Family B,
;; we need to iterate 15 times (for j from 0 to 14) to get 30 nuggets.
;; The nuggets generated from Family A are always smaller than those from Family B for the same iteration j.
;; We collect all 30 nuggets, sort them, and then sum them up.

#|(defun solve ()
  (let ((golden-nuggets '())
        ;; Initial (Y, k) values for the two families
        (y-a 17) (k-a 7)  ; Corresponds to N=2 for j=0
        (y-b 32) (k-b 14) ; Corresponds to N=5 for j=0
        ;; (p_F, q_F) from (9+4*sqrt(5))^2 = 161+72*sqrt(5)
        (p-f 161) (q-f 72))

    ;; Generate 15 nuggets from each family, for a total of 30.
    (loop for j from 0 to 14 do
      ;; Calculate N for the current (y-a, k-a) pair and add to list.
      (let ((n-a (/ (- y-a 7) 5)))
        (push n-a golden-nuggets))

      ;; Calculate N for the current (y-b, k-b) pair and add to list.
      (let ((n-b (/ (- y-b 7) 5)))
        (push n-b golden-nuggets))

      ;; Update (y-a, k-a) for the next iteration using the recurrence relations.
      (let ((next-y-a (+ (* p-f y-a) (* 5 q-f k-a)))
            (next-k-a (+ (* q-f y-a) (* p-f k-a))))
        (setf y-a next-y-a
              k-a next-k-a))

      ;; Update (y-b, k-b) for the next iteration using the recurrence relations.
      (let ((next-y-b (+ (* p-f y-b) (* 5 q-f k-b)))
            (next-k-b (+ (* q-f y-b) (* p-f k-b))))
        (setf y-b next-y-b
              k-b next-k-b)))

    ;; Sort the collected nuggets in ascending order.
    ;; This ensures they are ordered correctly, as required by "first thirty".
    (setf golden-nuggets (sort golden-nuggets #'<))

    ;; Sum the first thirty golden nuggets.
    (apply #'+ golden-nuggets)))|#

(defun solve ()
  (let ((golden-nuggets '())
        ;; 6つのすべてのファミリの初期値 (Y, k)
        (seeds '((17 7)     ; -> N = 2
                 (32 14)    ; -> N = 5
                 (112 50)   ; -> N = 21
                 (217 97)   ; -> N = 42
                 (7 1)      ; -> N = 0 (ループ内で N > 0 で弾く)
                 (767 343))) ; -> N = 152
        ;; (9+4*sqrt(5))^2 = 161+72*sqrt(5)
        (p-f 161) (q-f 72))

    (dolist (seed seeds)
      (let ((y (first seed))
            (k (second seed)))
        ;; 各ファミリから十分に解を生成 (15個ずつ)
        (loop repeat 15 do
                (let ((n (/ (- y 7) 5)))
                  ;; Nが正の整数の場合のみ追加 (N=0を除外)
                  (when (> n 0)
                    (push n golden-nuggets)))

                ;; (y, k) を次の値に更新
                (let ((next-y (+ (* p-f y) (* 5 q-f k)))
                      (next-k (+ (* q-f y) (* p-f k))))
                  (setf y next-y
                        k next-k)))))

    ;; 昇順にソートし、最初の30個を取り出して合計する
    (setf golden-nuggets (sort golden-nuggets #'<))
    (apply #'+ (subseq golden-nuggets 0 30))))


#+| Do it | (solve )
;→ 5673835352990

:fix
