;;; -*- mode: Lisp; coding: utf-8 -*-
;;; llm-model: gemini-3.1-pro
(cl:in-package cl-user)
(defpackage #:project-euler-0416 (:use cl series alexandria) (:export #:solve))
(in-package #:project-euler-0416)
(eval-when (:compile-toplevel :load-toplevel :execute) (series::install))
;(declaim (optimize (speed 3) (safety 0) (debug 0)))

(defmacro make-uint64-array (dims)
  `(make-array ,dims :element-type '(unsigned-byte 64) :initial-element 0))

(defun build-binom ()
  (let ((binom (make-uint64-array '(25 25))))
    (iterate ((i (scan-range :below 25)))
      (setf (aref binom i 0) 1)
      (iterate ((j (scan-range :from 1 :upto i)))
        (setf (aref binom i j)
              (mod (+ (aref binom (1- i) (1- j))
                      (aref binom (1- i) j))
                   #.(expt 10 9)))))
    binom))

(defun state-index (c1 c2 m)
  (let ((idx 0))
    (iterate ((i (scan-range :below c1)))
      (incf idx (- (+ (* 2 m) 1) i)))
    (+ idx c2)))

(defun build-a-b (m)
  (let* ((size (truncate (* (+ (* 2 m) 1) (+ (* 2 m) 2)) 2))
         (a-mat (make-uint64-array (list size size)))
         (b-mat (make-uint64-array (list size size)))
         (binom (build-binom)))
    (iterate ((c1 (scan-range :from 0 :upto (* 2 m))))
      (iterate ((c2 (scan-range :from 0 :upto (- (* 2 m) c1))))
        (let ((c0 (- (* 2 m) c1 c2))
              (idx-base (state-index c1 c2 m)))
          (iterate ((c1-prime (scan-range :from 0 :upto c0)))
            (iterate ((c2-prime (scan-range :from 0 :upto c1)))
              (let* ((c0-prime (- (* 2 m) c1-prime c2-prime))
                     (weight (mod (* (aref binom c0 c1-prime)
                                     (aref binom c1 c2-prime))
                                  #.(expt 10 9)))
                     (idx-prime-base (state-index c1-prime c2-prime m)))
                (if (= c0-prime 0)
                    ;; 未訪問マスが発生する遷移は B 行列に記録
                    (setf (aref b-mat idx-base idx-prime-base)
                          (mod (+ (aref b-mat idx-base idx-prime-base) weight)
                               #.(expt 10 9)))
                    ;; 未訪問マスが発生しない遷移は A 行列に記録
                    (setf (aref a-mat idx-base idx-prime-base)
                          (mod (+ (aref a-mat idx-base idx-prime-base) weight)
                               #.(expt 10 9))))))))))
    (cons a-mat b-mat)))

(defun matrix-multiply (x y size)
  (let ((z (make-uint64-array (list size size)))
        (y-t (make-uint64-array (list size size))))
    ;; キャッシュ効率最大化のための転置
    (iterate ((i (scan-range :below size)))
      (iterate ((j (scan-range :below size)))
        (setf (aref y-t j i) (aref y i j))))
    (iterate ((i (scan-range :below size)))
      (iterate ((j (scan-range :below size)))
        (let ((sum 0))
          (declare (type (unsigned-byte 64) sum))
          (iterate ((k (scan-range :below size)))
            (setf sum (+ sum (* (aref x i k) (aref y-t j k))))
            ;; 16回ごとに剰余を取ることで 64-bit オーバーフローを完全に回避
            (when (= (logand k 15) 15)
              (setf sum (mod sum #.(expt 10 9)))))
          (setf (aref z i j) (mod sum #.(expt 10 9))))))
    z))

(defun matrix-add (x y size)
  (let ((z (make-uint64-array (list size size))))
    (iterate ((i (scan-range :below size)))
      (iterate ((j (scan-range :below size)))
        (setf (aref z i j) (mod (+ (aref x i j) (aref y i j)) #.(expt 10 9)))))
    z))

(defun power-a-b (a b exp size)
  ;; M = [[A, B], [0, A]] の累乗を半分のサイズ (A_k, C_k) に分解して再帰計算する超次元崩壊
  (labels ((recur (k)
             (if (= k 1)
                 (cons a b)
                 (let* ((half (recur (ash k -1)))
                        (ah (car half))
                        (ch (cdr half))
                        (a2 (matrix-multiply ah ah size))
                        (c2 (matrix-add (matrix-multiply ah ch size)
                                        (matrix-multiply ch ah size) size)))
                   (if (oddp k)
                       (cons (matrix-multiply a2 a size)
                             (matrix-add (matrix-multiply a2 b size)
                                         (matrix-multiply c2 a size) size))
                       (cons a2 c2))))))
    (recur exp)))

(defun f (m n)
  (let* ((mats (build-a-b m))
         (a-mat (car mats))
         (b-mat (cdr mats))
         (size (truncate (* (+ (* 2 m) 1) (+ (* 2 m) 2)) 2))
         (res (power-a-b a-mat b-mat (- n 1) size))
         (ak (car res))
         (ck (cdr res)))
    ;; 始点から終点まで、未訪問が0回 (A^k) と未訪問が1回 (C_k) のパターンの和
    (mod (+ (aref ak 0 0) (aref ck 0 0)) #.(expt 10 9))))

(defun solve ()
  (format t "観測: テストケース T(1, 3) を検証中...~%")
  (format t "T(1, 3) = ~A (Expected: 4)~%" (f 1 3))
  (format t "観測: テストケース T(1, 4) を検証中...~%")
  (format t "T(1, 4) = ~A (Expected: 15)~%" (f 1 4))
  (format t "観測: テストケース T(1, 5) を検証中...~%")
  (format t "T(1, 5) = ~A (Expected: 46)~%" (f 1 5))
  (format t "観測: テストケース T(2, 3) を検証中...~%")
  (format t "T(2, 3) = ~A (Expected: 16)~%" (f 2 3))
  
  (format t "観測: 本探索 F(10, 10^12) を実行中...~%")
  (let ((ans (f 10 #.(expt 10 12))))
    (format t "Answer: ~9,'0D~%" ans)
    ans))

#+| Do it | (project-euler-0416:solve)