;;; -*- mode: Lisp; coding: utf-8  -*-
;;; llm-model: gemini-3-flash-preview
(cl:in-package cl-user)
(defpackage #:project-euler-0428 (:use cl iterate alexandria) (:export #:solve))
(in-package #:project-euler-0428)

(defmacro optimized-code-p (boole)
  (typecase boole
    (null nil)
    (T `(declaim (optimize (speed 3) (safety 0) (debug 0) #+lispworks (hcl:fixnum-safety 0))))))

(optimized-code-p nil)


(defun solve (&optional (limit 1000000000))
  (let* ((sq (isqrt limit))
         (sq-size (1+ sq))
         (tau (make-array sq-size :element-type 'fixnum :initial-element 0))
         (S2  (make-array sq-size :element-type 'fixnum :initial-element 0))
         (mu  (make-array sq-size :element-type 'fixnum :initial-element 0))
         (D   (make-array sq-size :element-type 'fixnum :initial-element 0))
         (SD  (make-array sq-size :element-type 'fixnum :initial-element 0)))
    (declare (type (simple-array fixnum (*)) tau S2 mu D SD))
    
    ;; 1. 基本的な数論的関数の事前計算 (O(sqrt(N) log sqrt(N)))
    (iterate (for i from 1 to sq)
      (iterate (for j from i to sq by i)
        (incf (aref tau j))))
        
    (iterate (for i from 1 to sq)
      (setf (aref S2 i) (+ (aref S2 (1- i)) (aref tau i))))

    (setf (aref mu 1) 1)
    (iterate (for i from 1 to sq)
      (let ((m (aref mu i)))
        (unless (zerop m)
          (iterate (for j from (* 2 i) to sq by i)
            (decf (aref mu j) m)))))

    (iterate (for i from 1 to sq)
      (let ((chi (cond ((zerop (mod i 3)) 0)
                       ((= 1 (mod i 3)) 1)
                       (t -1))))
        (setf (aref D i) (* (aref tau i) chi))
        (setf (aref SD i) (+ (aref SD (1- i)) (aref D i)))))

    (labels ((get-S2 (y)
               (let* ((K (isqrt y)) (ans 0))
                 (declare (type integer y K ans))
                 (iterate (for i from 1 to K)
                   (incf ans (* 2 (floor y i))))
                 (- ans (* K K))))

             (get-S3 (y)
               (if (<= y 0) (return-from get-S3 0))
               (let* ((K (isqrt y)) (ans 0))
                 (declare (type integer y K ans))
                 (iterate (for a from 1 to K)
                   (incf ans (* (aref tau a) (floor y a))))
                 (iterate (for b from 1 to (floor y K))
                   (incf ans (get-S2 (floor y b))))
                 (- ans (* (get-S2 K) (floor y K)))))

             (get-Sf (x)
               (if (<= x 0) (return-from get-Sf 0))
               (let ((ans 0) (K (isqrt x)))
                 (declare (type integer x K ans))
                 (iterate (for d from 1 to K)
                   (let ((m (aref mu d)))
                     (unless (zerop m)
                       (incf ans (* m (get-S3 (floor x (* d d))))))))
                 ans))

             ;; g1(n) = tau(2n^2) の和 (k=4 相当)
             (get-Sg1 (x)
               (let ((ans 0))
                 (iterate (for k from 0)
                   (let ((pw (expt 2 k)))
                     (if (> pw x) (finish))
                     (let ((hk (* 2 (if (evenp k) 1 -1))))
                       (incf ans (* hk (get-Sf (floor x pw)))))))
                 ans))

             ;; g2(n) = tau(12n^2) の和 (k=3 相当)
             (get-Sg2 (x)
               (let ((ans 0))
                 (iterate (for a from 0)
                   (let ((p2 (expt 2 a)))
                     (if (> p2 x) (finish))
                     (let ((h2 (if (= a 0) 3 (* 4 (if (evenp a) 1 -1)))))
                       (iterate (for b from 0)
                         (let ((p3 (expt 3 b)))
                           (if (> (* p2 p3) x) (finish))
                           (let ((h3 (* 2 (if (evenp b) 1 -1))))
                             (incf ans (* h2 h3 (get-Sf (floor x (* p2 p3)))))))))))
                 ans))

             (get-SU (x)
               (let ((ans 0))
                 (iterate (for a from 0)
                   (let ((p2 (expt 2 a)))
                     (if (> p2 x) (finish))
                     (let ((h2 (if (= a 0) 3 (* 4 (if (evenp a) 1 -1)))))
                       (iterate (for b from 0)
                         (let ((p3 (expt 3 b)))
                           (if (> (* p2 p3) x) (finish))
                           (let ((h4 (cond ((= b 0) 1)
                                           ((= b 1) -3)
                                           (t (* 4 (if (evenp b) 1 -1))))))
                             (incf ans (* h2 h4 (get-Sf (floor x (* p2 p3)))))))))))
                 ans))

             (get-SD (y)
               (if (<= y sq)
                   (aref SD y)
                   (error "Array Out of Bounds: SD called with ~A > ~A" y sq)))

             (get-SB (y)
               (if (<= y 0) (return-from get-SB 0))
               (let* ((K (isqrt y)) (ans 0))
                 (declare (type integer y K ans))
                 (iterate (for n from 1 to K)
                   (incf ans (* (aref D n) (floor y n))))
                 (iterate (for n from 1 to (floor y K))
                   (incf ans (get-SD (floor y n))))
                 (- ans (* (get-SD K) (floor y K)))))

             (get-SB3 (y)
               (- (get-SB y) (get-SB (floor y 3))))

             (get-SV (x)
               (if (<= x 0) (return-from get-SV 0))
               (let ((ans 0) (K (isqrt x)))
                 (iterate (for d from 1 to K)
                   (when (/= (mod d 3) 0)
                     (let ((m (aref mu d)))
                       (unless (zerop m)
                         (incf ans (* m (get-SB3 (floor x (* d d)))))))))
                 ans))

             ;; g3(n) = h(n) の和 (k=6 相当)
             (get-Sg3 (x)
               (let ((ans (- (get-SU x) (get-SV x))))
                 (setf ans (/ ans 2))
                 (iterate (for k from 1)
                   (let ((p3 (expt 3 k)))
                     (if (> p3 x) (finish))
                     (incf ans (* 2 k (get-SU (floor x p3))))))
                 ans)))

      ;; 2. ディリクレ双曲線法による集約
      (let ((ans1 (get-Sg1 limit))
            (ans2 (get-Sg2 limit))
            (ans3 (get-Sg3 limit)))
        (format t "Observation (N=~A):~%" limit)
        (format t "  k=4 Triplets: ~A~%" ans1)
        (format t "  k=3 Triplets: ~A~%" ans2)
        (format t "  k=6 Triplets: ~A~%" ans3)
        (format t "--------------------------------~%")
        (+ ans1 ans2 ans3)))))


#+| Do it | (solve )