;;; -*- mode: Lisp; coding: utf-8  -*-
;;; llm-model: gemini-3.1-pro
(cl:in-package cl-user)
(defpackage #:project-euler-0968 (:use cl iterate alexandria) (:export #:solve))
(in-package #:project-euler-0968)

#||
(clif-logic
  (formal-problem "Project Euler 968: Fractional Matching Polytope Sum")
  (invariants
    (polytope-complexity 
      (implies (and (>= x_i 0) (<= (+ x_i x_j) B_ij))
               (fractional-matching-polytope x)))
    (utvpi-closure
      (always (subset (coefficients generated_constraints) (set -1 0 1))))
    (half-integral-normalization
      (equal (integer-solutions (<= (+ (* 2 x) (* -2 y)) C))
             (integer-solutions (<= (+ x (- y)) (floor C 2))))))
  (optimizations
    (iterated-summation "Analytically integrates variables using sum(R^x) = (R^{U+1} - R^L)/(R - 1) resolving O(B^5) to O(V).")
    (global-normalization "Corrected normalization to globally divide ALL coefficients by 2 when any coefficient hits bounds, preventing UTVPI tree corruption and NIL leakage.")
    (type-safety "Strict fixnum arrays and (or X 0) fallbacks to guarantee no NIL propagation during empty region pruning.")))
||#


(declaim (inline is-constant-negative normalize-constraint))

(defun is-constant-negative (expr)
  "Checks if the constraint expr >= 0 is a contradictory negative constant."
  (and (= 0 (aref expr 1)) (= 0 (aref expr 2))
       (= 0 (aref expr 3)) (= 0 (aref expr 4))
       (= 0 (aref expr 5)) (< (aref expr 0) 0)))

(defun normalize-constraint (expr)
  "Globally normalizes coefficients of 2 or -2 generated by the half-integrality."
  (let ((has-two nil))
    (iterate (for i from 1 to 5)
      (when (or (>= (aref expr i) 2) (<= (aref expr i) -2))
        (setf has-two t)))
    (when has-two
      (setf (aref expr 0) (floor (aref expr 0) 2))
      (iterate (for i from 1 to 5)
        (setf (aref expr i) (truncate (aref expr i) 2)))))
  expr)

(defun dfs (var-idx constraints)
  "Explores all valid UTVPI bound assignments using DFS with instant constant-pruning."
  (let ((L nil) (U nil) (other nil))
    (iterate (for c in constraints)
      (cond ((> (aref c var-idx) 0)
             (let ((expr (copy-seq c)))
               (setf (aref expr var-idx) 0)
               (iterate (for i from 0 to 5)
                 (unless (= i var-idx)
                   (setf (aref expr i) (- (aref expr i)))))
               (push expr L)))
            ((< (aref c var-idx) 0)
             (let ((expr (copy-seq c)))
               (setf (aref expr var-idx) 0)
               (push expr U)))
            (t (push c other))))
    
    (let ((regions nil)
          (k-idx 0))
      (iterate (for L-kstar in L)
        (let ((m-idx 0))
          (iterate (for U-mstar in U)
            (let ((new-constraints (copy-list other))
                  (valid t))
              
              ;; L_{k^*} >= L_k
              (let ((k 0))
                (iterate (for L-k in L)
                  (unless (= k k-idx)
                    (let ((expr (make-array 6 :element-type 'fixnum)))
                      (iterate (for i from 0 to 5)
                        (setf (aref expr i) (- (aref L-kstar i) (aref L-k i))))
                      (when (< k k-idx) (decf (aref expr 0)))
                      (normalize-constraint expr)
                      (if (is-constant-negative expr)
                          (setf valid nil)
                          (push expr new-constraints))))
                  (incf k)))
              
              ;; U_m >= U_{m^*}
              (when valid
                (let ((m 0))
                  (iterate (for U-m in U)
                    (unless (= m m-idx)
                      (let ((expr (make-array 6 :element-type 'fixnum)))
                        (iterate (for i from 0 to 5)
                          (setf (aref expr i) (- (aref U-m i) (aref U-mstar i))))
                        (when (< m m-idx) (decf (aref expr 0)))
                        (normalize-constraint expr)
                        (if (is-constant-negative expr)
                            (setf valid nil)
                            (push expr new-constraints))))
                    (incf m))))
              
              ;; U_{m^*} >= L_{k^*}
              (when valid
                (let ((expr (make-array 6 :element-type 'fixnum)))
                  (iterate (for i from 0 to 5)
                    (setf (aref expr i) (- (aref U-mstar i) (aref L-kstar i))))
                  (normalize-constraint expr)
                  (if (is-constant-negative expr)
                      (setf valid nil)
                      (push expr new-constraints))))
              
              (when valid
                (if (< var-idx 5)
                    (let ((sub (dfs (1+ var-idx) new-constraints)))
                      (iterate (for s in sub)
                        (when s
                          (push (cons (list L-kstar U-mstar) s) regions))))
                    (push (list (list L-kstar U-mstar)) regions))))
            (incf m-idx)))
        (incf k-idx))
      regions)))

(defun mod-inverse (a m)
  (let ((t-val 0) (newt 1)
        (r m) (newr (mod a m)))
    (iterate (while (not (= newr 0)))
      (let* ((quotient (truncate r newr))
             (tmp-t (- t-val (* quotient newt)))
             (tmp-r (- r (* quotient newr))))
        (setf t-val newt)
        (setf newt tmp-t)
        (setf r newr)
        (setf newr tmp-r)))
    (if (< t-val 0) (+ t-val m) t-val)))

(defun power (base exp)
  (if (< exp 0)
      (power (mod-inverse base 1000000007) (- exp))
      (let ((res 1)
            (b (mod base 1000000007)))
        (iterate (while (> exp 0))
          (when (oddp exp) (setf res (mod (* res b) 1000000007)))
          (setf b (mod (* b b) 1000000007))
          (setf exp (ash exp -1)))
        res)))

(defun evaluate-region (region)
  "Analytically evaluates the sum over a specific polytope cell. Safe against NILs."
  (if (or (null region) (not (= (length region) 5)))
      0
      (let ((terms (list (list 1 (make-array 6 :initial-contents '(0 2 3 5 7 11))))))
        (iterate (for i from 1 to 5)
          (let* ((bounds (nth (- i 1) region))
                 (L (first bounds))
                 (U (second bounds))
                 (new-terms nil))
            (iterate (for term in terms)
              (let* ((C (or (first term) 0))
                     (R (second term))
                     (R-k (aref R i)))
                (if (= R-k 1)
                    (push (list 0 R) new-terms) ; Divergence fallback (rare/impossible logically)
                    (let ((inv (mod-inverse (mod (- R-k 1) 1000000007) 1000000007)))
                      ;; Term A (Upper Bound)
                      (let* ((CA (mod (* C R-k) 1000000007)))
                        (setf CA (mod (* CA inv) 1000000007))
                        (setf CA (mod (* CA (power R-k (aref U 0))) 1000000007))
                        (let ((RA (copy-seq R)))
                          (iterate (for j from (1+ i) to 5)
                            (setf (aref RA j) (mod (* (aref RA j) (power R-k (aref U j))) 1000000007)))
                          (push (list CA RA) new-terms)))
                      ;; Term B (Lower Bound)
                      (let* ((CB (mod (* C (- inv)) 1000000007)))
                        (setf CB (mod (* CB (power R-k (aref L 0))) 1000000007))
                        (let ((RB (copy-seq R)))
                          (iterate (for j from (1+ i) to 5)
                            (setf (aref RB j) (mod (* (aref RB j) (power R-k (aref L j))) 1000000007)))
                          (push (list CB RB) new-terms)))))))
            (setf terms new-terms)))
        (let ((sum 0))
          (iterate (for term in terms)
            (setf sum (mod (+ sum (or (first term) 0)) 1000000007)))
          sum))))

(defun generate-a ()
  (let ((a (make-array 1000 :element-type 'fixnum)))
    (setf (aref a 0) 1)
    (setf (aref a 1) 7)
    (iterate (for i from 2 to 999)
      (setf (aref a i) (mod (+ (* 7 (aref a (- i 1))) 
                               (mod (* (aref a (- i 2)) (aref a (- i 2))) 1000000007))
                            1000000007)))
    a))

(defun get-q (n a-array)
  (let ((initial-constraints (make-array 15 :initial-element nil))
        (idx 0))
    (iterate (for i from 1 to 5)
      (let ((c (make-array 6 :initial-element 0 :element-type 'fixnum)))
        (setf (aref c i) 1)
        (setf (aref initial-constraints idx) c)
        (incf idx)))
    (let ((b-idx (* 10 n)))
      (iterate (for i from 1 to 4)
        (iterate (for j from (+ i 1) to 5)
          (let ((c (make-array 6 :initial-element 0 :element-type 'fixnum)))
            (setf (aref c 0) (aref a-array b-idx))
            (setf (aref c i) -1)
            (setf (aref c j) -1)
            (setf (aref initial-constraints idx) c)
            (incf idx)
            (incf b-idx)))))
    (let ((regions (dfs 1 (coerce initial-constraints 'list)))
          (total 0))
      (iterate (for r in regions)
        (when r
          (setf total (mod (+ total (or (evaluate-region r) 0)) 1000000007))))
      total)))

(defun solve ()
  "Evaluates sum of Q(n) for 0 <= n < 100"
  (let ((a-array (generate-a))
        (total-sum 0))
    (iterate (for n from 0 to 99)
      (let ((qn (or (get-q n a-array) 0)))
        (setf total-sum (mod (+ total-sum qn) 1000000007))
        (when (zerop (mod (1+ n) 20))
          (format t "[Log] Evaluated Q(0) to Q(~A)... Current Sum: ~A~%" n total-sum)
          (finish-output))))
    total-sum))


#+| Do it | (solve )
#|------------------------------------------------------------|
Timing the evaluation of (solve)
[Log] Evaluated Q(0) to Q(19)... Current Sum: 502237211
[Log] Evaluated Q(0) to Q(39)... Current Sum: 524761895
[Log] Evaluated Q(0) to Q(59)... Current Sum: 804280989
[Log] Evaluated Q(0) to Q(79)... Current Sum: 526425656
[Log] Evaluated Q(0) to Q(99)... Current Sum: 885362394

User time    =        4.182
System time  =        0.040
Elapsed time =        4.157
Allocation   = 717990056 bytes
650 Page faults
GC time      =        0.011
 |------------------------------------------------------------|#
;;→ 885362394
:ok