;;; -*- mode: Lisp; coding: utf-8  -*-
;;; llm-model: gemini-3.1-pro
(cl:in-package cl-user)
(defpackage #:project-euler-0989 (:use cl iterate alexandria) (:export #:solve))
(in-package #:project-euler-0989)

(defmacro optimized-code-p (boole)
  (typecase boole
    (null nil)
    (T `(declaim (optimize (speed 3) (safety 0) (debug 0) #+lispworks (hcl:fixnum-safety 0))))))

(optimized-code-p T)

(defconstant +MOD+ 1000000009)
(defconstant +TARGET-LIMIT+ #.(expt 10 14))
(defconstant +SMALL-NONPRIMITIVE-LIMIT+ 8)

(defmacro mod-add (a b)
  `(let ((s (+ ,a ,b)))
     (declare (type fixnum s))
     (if (>= s +MOD+) (- s +MOD+) s)))

(defmacro mod-sub (a b)
  `(let ((d (- ,a ,b)))
     (declare (type fixnum d))
     (if (< d 0) (+ d +MOD+) d)))

(defmacro mod-mul (a b)
  `(mod (* ,a ,b) +MOD+))

(defun mod-pow (base exp)
  (declare (type fixnum base exp))
  (let ((res 1) (b base) (e exp))
    (declare (type fixnum res b e))
    (iterate (while (> e 0))
      (when (oddp e) (setf res (mod-mul res b)))
      (setf b (mod-mul b b))
      (setf e (ash e -1)))
    res))

(defun mod-inv (n)
  (declare (type fixnum n))
  (mod-pow n (- +MOD+ 2)))

(defun tonelli-shanks (n p)
  (declare (type fixnum n p))
  (when (= n 0) (return-from tonelli-shanks 0))
  (when (/= (mod-pow n (truncate (- p 1) 2)) 1)
    (error "not a quadratic residue"))
  (when (= (mod p 4) 3)
    (return-from tonelli-shanks (mod-pow n (truncate (+ p 1) 4))))
  (let* ((q (- p 1))
         (s 0))
    (iterate (while (evenp q))
      (setf q (truncate q 2))
      (incf s))
    (let ((z 2))
      (iterate (while (/= (mod-pow z (truncate (- p 1) 2)) (- p 1)))
        (incf z))
      (let ((m s)
            (c (mod-pow z q))
            (t-val (mod-pow n q))
            (r (mod-pow n (truncate (+ q 1) 2))))
        (declare (type fixnum m c t-val r))
        (iterate (while (/= t-val 1))
          (let ((i 1)
                (t2i (mod-mul t-val t-val)))
            (iterate (while (/= t2i 1))
              (setf t2i (mod-mul t2i t2i))
              (incf i))
            (let ((b (mod-pow c (ash 1 (- m i 1)))))
              (setf r (mod-mul r b))
              (setf c (mod-mul b b))
              (setf t-val (mod-mul t-val c))
              (setf m i))))
        r))))

(defun build-small-nonprimitive-terms (max-limit)
  (declare (type fixnum max-limit))
  (let* ((max-a (+ (* 2 (isqrt max-limit)) 2))
         (values (make-array 0 :element-type 'fixnum :fill-pointer 0 :adjustable t)))
    (iterate (for a from 2 to max-a)
      (iterate (for b from 1 to (truncate a 2))
        (let ((q (- (* a a) (* a b) (* b b))))
          (when (and (> q 0) (<= q max-limit))
            (vector-push-extend q values)))))
    (setf values (sort values #'<))
    (let ((terms (make-array (1+ max-limit)))
          (prefix (make-array 0 :element-type 'fixnum :fill-pointer 0 :adjustable t))
          (idx 0)
          (total (length values)))
      (iterate (for limit from 0 to max-limit)
        (iterate (while (and (< idx total) (<= (aref values idx) limit)))
          (vector-push-extend (aref values idx) prefix)
          (incf idx))
        (setf (aref terms limit) (make-array (length prefix) :element-type 'fixnum :initial-contents prefix)))
      terms)))

(defvar *small-nonprimitive-terms* (build-small-nonprimitive-terms +SMALL-NONPRIMITIVE-LIMIT+))

(defun eval-small-nonprimitive-pair (limit z1 z2)
  (declare (type fixnum limit z1 z2))
  (let ((terms (aref *small-nonprimitive-terms* limit))
        (total1 0) (total2 0)
        (power1 1) (power2 1)
        (exponent 0))
    (declare (type fixnum total1 total2 power1 power2 exponent)
             (type (simple-array fixnum (*)) terms))
    (iterate (for target in-vector terms)
      (iterate (while (< exponent target))
        (setf power1 (mod-mul power1 z1))
        (setf power2 (mod-mul power2 z2))
        (incf exponent))
      (setf total1 (mod-add total1 power1))
      (setf total2 (mod-add total2 power2)))
    (values total1 total2)))

(defun mobius-sieve (limit)
  (declare (type fixnum limit))
  (let ((mu (make-array (1+ limit) :element-type '(signed-byte 8) :initial-element 1))
        (is-prime (make-array (1+ limit) :element-type 'bit :initial-element 1)))
    (when (>= limit 0) (setf (aref is-prime 0) 0))
    (when (>= limit 1) (setf (aref is-prime 1) 0))
    (iterate (for p from 2 to limit)
      (when (= (aref is-prime p) 1)
        (iterate (for multiple from p to limit by p)
          (setf (aref mu multiple) (- (aref mu multiple))))
        (let ((square (* p p)))
          (when (<= square limit)
            (iterate (for multiple from square to limit by square)
              (setf (aref mu multiple) 0))
            (iterate (for multiple from square to limit by p)
              (setf (aref is-prime multiple) 0))))
        (iterate (for multiple from (+ p p) to limit by p)
          (setf (aref is-prime multiple) 0))))
    mu))

(defun nonprimitive-pair (limit z1 z1-inv z2 z2-inv)
  (declare (type fixnum limit z1 z1-inv z2 z2-inv))
  (if (<= limit +SMALL-NONPRIMITIVE-LIMIT+)
      (eval-small-nonprimitive-pair limit z1 z2)
      (let* ((total1 0) (total2 0)
             (z1-sq (mod-mul z1 z1)) (z2-sq (mod-mul z2 z2))
             (z1-inv-sq (mod-mul z1-inv z1-inv)) (z2-inv-sq (mod-mul z2-inv z2-inv))
             (z1-inv-4 (mod-mul z1-inv-sq z1-inv-sq)) (z2-inv-4 (mod-mul z2-inv-sq z2-inv-sq))
             (z1-inv-5 (mod-mul z1-inv-4 z1-inv)) (z2-inv-5 (mod-mul z2-inv-4 z2-inv))
             (z1-inv-10 (mod-mul z1-inv-5 z1-inv-5)) (z2-inv-10 (mod-mul z2-inv-5 z2-inv-5))
             (z1-inv-15 (mod-mul z1-inv-10 z1-inv-5)) (z2-inv-15 (mod-mul z2-inv-10 z2-inv-5)))
        (declare (type fixnum total1 total2 z1-sq z2-sq z1-inv-sq z2-inv-sq
                       z1-inv-4 z2-inv-4 z1-inv-5 z2-inv-5 z1-inv-10 z2-inv-10 z1-inv-15 z2-inv-15))
        
        ;; Even weight window z^(m^2)
        (let ((even-weight1 z1-inv-5) (even-weight2 z2-inv-5)
              (even-delta1 z1-inv-15) (even-delta2 z2-inv-15)
              (add-index 0) (add-term1 1) (add-term2 1)
              (add-step1 z1) (add-step2 z2)
              (drop-index 0) (drop-term1 1) (drop-term2 1)
              (drop-step1 z1) (drop-step2 z2)
              (window1 0) (window2 0)
              (t-val 1) (lower 3) (upper 0)
              (rhs (+ limit 5)))
          (declare (type fixnum even-weight1 even-weight2 even-delta1 even-delta2
                         add-index add-term1 add-term2 add-step1 add-step2
                         drop-index drop-term1 drop-term2 drop-step1 drop-step2
                         window1 window2 t-val lower upper rhs))
          (iterate (while (<= (* (1+ upper) (1+ upper)) rhs))
            (incf upper))
          (iterate (while (<= lower upper))
            (iterate (while (<= add-index upper))
              (setf window1 (mod-add window1 add-term1))
              (setf window2 (mod-add window2 add-term2))
              (setf add-term1 (mod-mul add-term1 add-step1))
              (setf add-step1 (mod-mul add-step1 z1-sq))
              (setf add-term2 (mod-mul add-term2 add-step2))
              (setf add-step2 (mod-mul add-step2 z2-sq))
              (incf add-index))
            (iterate (while (< drop-index lower))
              (setf window1 (mod-sub window1 drop-term1))
              (setf window2 (mod-sub window2 drop-term2))
              (setf drop-term1 (mod-mul drop-term1 drop-step1))
              (setf drop-step1 (mod-mul drop-step1 z1-sq))
              (setf drop-term2 (mod-mul drop-term2 drop-step2))
              (setf drop-step2 (mod-mul drop-step2 z2-sq))
              (incf drop-index))
            
            (setf total1 (mod-add total1 (mod-mul window1 even-weight1)))
            (setf total2 (mod-add total2 (mod-mul window2 even-weight2)))
            
            (setf even-weight1 (mod-mul even-weight1 even-delta1))
            (setf even-delta1 (mod-mul even-delta1 z1-inv-10))
            (setf even-weight2 (mod-mul even-weight2 even-delta2))
            (setf even-delta2 (mod-mul even-delta2 z2-inv-10))
            
            (incf rhs (+ (* 10 t-val) 5))
            (incf t-val)
            (incf lower 3)
            (iterate (while (<= (* (1+ upper) (1+ upper)) rhs))
              (incf upper))))
        
        ;; Odd weight window z^(m(m+1))
        (let ((odd-weight1 z1-inv) (odd-weight2 z2-inv)
              (odd-delta1 z1-inv-10) (odd-delta2 z2-inv-10)
              (add-index 0) (add-term1 1) (add-term2 1)
              (add-step1 z1-sq) (add-step2 z2-sq)
              (drop-index 0) (drop-term1 1) (drop-term2 1)
              (drop-step1 z1-sq) (drop-step2 z2-sq)
              (window1 0) (window2 0)
              (t-val 0) (lower 1) (upper 0)
              (rhs (+ limit 1)))
          (declare (type fixnum odd-weight1 odd-weight2 odd-delta1 odd-delta2
                         add-index add-term1 add-term2 add-step1 add-step2
                         drop-index drop-term1 drop-term2 drop-step1 drop-step2
                         window1 window2 t-val lower upper rhs))
          (iterate (while (<= (* (1+ upper) (+ upper 2)) rhs))
            (incf upper))
          (iterate (while (<= lower upper))
            (iterate (while (<= add-index upper))
              (setf window1 (mod-add window1 add-term1))
              (setf window2 (mod-add window2 add-term2))
              (setf add-term1 (mod-mul add-term1 add-step1))
              (setf add-step1 (mod-mul add-step1 z1-sq))
              (setf add-term2 (mod-mul add-term2 add-step2))
              (setf add-step2 (mod-mul add-step2 z2-sq))
              (incf add-index))
            (iterate (while (< drop-index lower))
              (setf window1 (mod-sub window1 drop-term1))
              (setf window2 (mod-sub window2 drop-term2))
              (setf drop-term1 (mod-mul drop-term1 drop-step1))
              (setf drop-step1 (mod-mul drop-step1 z1-sq))
              (setf drop-term2 (mod-mul drop-term2 drop-step2))
              (setf drop-step2 (mod-mul drop-step2 z2-sq))
              (incf drop-index))
            
            (setf total1 (mod-add total1 (mod-mul window1 odd-weight1)))
            (setf total2 (mod-add total2 (mod-mul window2 odd-weight2)))
            
            (setf odd-weight1 (mod-mul odd-weight1 odd-delta1))
            (setf odd-delta1 (mod-mul odd-delta1 z1-inv-10))
            (setf odd-weight2 (mod-mul odd-weight2 odd-delta2))
            (setf odd-delta2 (mod-mul odd-delta2 z2-inv-10))
            
            (incf rhs (+ (* 10 t-val) 10))
            (incf t-val)
            (incf lower 3)
            (iterate (while (<= (* (1+ upper) (+ upper 2)) rhs))
              (incf upper))))
        (values total1 total2))))

(defun solve (&optional (limit +TARGET-LIMIT+))
  (let* ((sqrt5-mod (tonelli-shanks 5 +MOD+))
         (inv-sqrt5-mod (mod-inv sqrt5-mod))
         (inv2-mod (truncate (+ +MOD+ 1) 2))
         (phi-mod (mod-mul (mod-add 1 sqrt5-mod) inv2-mod))
         (phi-inv-mod (mod-inv phi-mod))
         (psi-mod (mod-mul (mod-sub 1 sqrt5-mod) inv2-mod))
         (phi-squared-mod (mod-mul phi-mod phi-mod))
         (phi-inv-squared-mod (mod-mul phi-inv-mod phi-inv-mod))
         (root (isqrt limit))
         (mu (mobius-sieve root))
         (p-phi 0) (p-psi 0)
         (phi-pow-g2 1) (phi-inv-pow-g2 1)
         (forward-step phi-mod) (backward-step phi-inv-mod)
         (g-square 1))
    (declare (type fixnum sqrt5-mod inv-sqrt5-mod inv2-mod phi-mod phi-inv-mod
                   psi-mod phi-squared-mod phi-inv-squared-mod root p-phi p-psi
                   phi-pow-g2 phi-inv-pow-g2 forward-step backward-step g-square)
             (type (simple-array (signed-byte 8) (*)) mu))
    
    (iterate (for g from 1 to root)
      (setf phi-pow-g2 (mod-mul phi-pow-g2 forward-step))
      (setf forward-step (mod-mul forward-step phi-squared-mod))
      (setf phi-inv-pow-g2 (mod-mul phi-inv-pow-g2 backward-step))
      (setf backward-step (mod-mul backward-step phi-inv-squared-mod))
      
      (let ((mu-g (aref mu g)))
        (when (/= mu-g 0)
          (let ((scaled-limit (truncate limit g-square))
                (psi-pow-g2 0) (psi-inv-pow-g2 0))
            (declare (type fixnum scaled-limit psi-pow-g2 psi-inv-pow-g2))
            (if (oddp g)
                (progn
                  (setf psi-pow-g2 (mod-sub 0 phi-inv-pow-g2))
                  (setf psi-inv-pow-g2 (mod-sub 0 phi-pow-g2)))
                (progn
                  (setf psi-pow-g2 phi-inv-pow-g2)
                  (setf psi-inv-pow-g2 phi-pow-g2)))
            
            (multiple-value-bind (np-phi np-psi)
                (nonprimitive-pair scaled-limit phi-pow-g2 phi-inv-pow-g2 psi-pow-g2 psi-inv-pow-g2)
              (declare (type fixnum np-phi np-psi))
              (if (= mu-g 1)
                  (progn
                    (setf p-phi (mod-add p-phi np-phi))
                    (setf p-psi (mod-add p-psi np-psi)))
                  (progn
                    (setf p-phi (mod-sub p-phi np-phi))
                    (setf p-psi (mod-sub p-psi np-psi))))))))
      (incf g-square (+ (* 2 g) 1)))
    
    (let ((ans (mod-mul (mod-sub p-phi p-psi) inv-sqrt5-mod)))
      (format t "Final Answer: ~A~%" ans)
      ans)))


#+| Do it | (solve )
#|------------------------------------------------------------|
Timing the evaluation of (solve)
Final Answer: 697845151

User time    =       36.274
System time  =        0.204
Elapsed time =       36.592
Allocation   = 11474336 bytes
8337 Page faults
GC time      =        0.005
 |------------------------------------------------------------|#
;;→ 697845151
:ok
