;;; -*- mode: Lisp; coding: utf-8  -*-
;;; llm-model: gemini-3.5-pro
(cl:in-package cl-user)
(defpackage #:project-euler-0891 (:use cl iterate alexandria) (:export #:solve))
(in-package #:project-euler-0891)

(defun solve ()
  (let* ((v1 1)
         (v2 12)
         (v3 720)
         
         ;; Differential coefficients independent of pi
         ;; a = v1 - v2
         ;; c = v2 - v3
         (a (- v1 v2))
         (c (- v2 v3))
         
         ;; Coefficients for each non-trivial permutation pi
         ;; b = -(v_pi(1) - v_pi(2)) = v_pi(2) - v_pi(1)
         ;; d = -(v_pi(2) - v_pi(3)) = v_pi(3) - v_pi(2)
         
         ;; pi_2 = (1 3 2) -> v_pi = (v1, v3, v2)
         (b2 (- v3 v1))
         (d2 (- v2 v3))
         
         ;; pi_3 = (2 1 3) -> v_pi = (v2, v1, v3)
         (b3 (- v1 v2))
         (d3 (- v3 v1))
         
         ;; pi_4 = (2 3 1) -> v_pi = (v2, v3, v1)
         (b4 (- v3 v2))
         (d4 (- v1 v3))
         
         ;; pi_5 = (3 1 2) -> Mathematically generates the exact same valid fractions as pi_4
         ;; so we only count the set generated by pi_4.
         
         ;; pi_6 = (3 2 1) -> v_pi = (v3, v2, v1)
         (b6 (- v2 v3))
         (d6 (- v1 v2))
         
         ;; Determinants (Size of Cyclic Groups N_pi)
         (det2 (abs (- (* a d2) (* c b2))))
         (det3 (abs (- (* a d3) (* c b3))))
         (det4 (abs (- (* a d4) (* c b4))))
         (det6 (abs (- (* a d6) (* c b6))))
         
         ;; Elements satisfying t1 = t2 (Size of E_pi to be strictly excluded)
         (k2 (abs (gcd (+ a b2) (+ c d2))))
         (k3 (abs (gcd (+ a b3) (+ c d3))))
         (k4 (abs (gcd (+ a b4) (+ c d4))))
         (k6 (abs (gcd (+ a b6) (+ c d6))))
         
         ;; Summation of disjoint valid sets (N_pi - K_pi)
         (ans (+ (- det2 k2)
                 (- det3 k3)
                 (- det4 k4)
                 (- det6 k6))))
                 
    (format t "pi_2 group size: ~A, excluded (t1=t2): ~A~%" det2 k2)
    (format t "pi_3 group size: ~A, excluded (t1=t2): ~A~%" det3 k3)
    (format t "pi_4 group size: ~A, excluded (t1=t2): ~A~%" det4 k4)
    (format t "pi_6 group size: ~A, excluded (t1=t2): ~A~%" det6 k6)
    (format t "Total ambiguous moments: ~A~%" ans)
    ans))

#+| Do it | (project-euler-0891:solve)
#|------------------------------------------------------------|
Timing the evaluation of (solve)
pi_2 group size: 516840, excluded (t1=t2): 708
pi_3 group size: 15697, excluded (t1=t2): 11
pi_4 group size: 509173, excluded (t1=t2): 1
pi_6 group size: 501143, excluded (t1=t2): 719
Total ambiguous moments: 1541414

User time    =        0.000
System time  =        0.000
Elapsed time =        0.000
Allocation   = 840 bytes
1 Page faults
GC time      =        0.000
 |------------------------------------------------------------|#
;;→ 1541414
:ok